### PR TITLE
Document GraphQLTelemetryProvider.SourceName

### LINKED ISSUE #3946: Not seeing any GraphQL telemetry with UseTelemetry
## Summary

I am probably missing something simple here, but I can't get telemetry working with graphql.

## Relevant information

Service configuration:
```csharp
    services
        .AddOpenTelemetry()
        .ConfigureResource(resource => resource.AddService("API"))
        .WithTracing(tracing => tracing
            .AddAspNetCoreInstrumentation()
            .AddHttpClientInstrumentation()
            .AddSqlClientInstrumentation()
            .AddConsoleExporter());

// later

        services.AddSingleton<IGraphQLExceptionHandler, ExceptionHandler>();
        services.AddGraphQL(builder => builder
            .AddSchema<MySchema>()
            .ConfigureExecutionOptions(options =>
            {
                var requestServices = options.RequestServices ?? throw new Exception("Missing RequestServices");
                var handler = requestServices.GetRequiredService<IGraphQLExceptionHandler>();
                options.UnhandledExceptionDelegate = ctx => handler.HandleException(ctx);
            })
            .AddSystemTextJson()
            .AddDataLoader()
            .AddGraphTypes(typeof(MySchema).Assembly)
            .UseTelemetry()
        );
```

I see http and sql traces, but nothing graphql. I'm not sure where to start debugging this!

### Environment (if relevant)

dotnet 8.0

### PR DESCRIPTION
**Pull request by gao-artur**
Fixes #3946

### CODE REVIEW

File: src/GraphQL/Extensions/GraphQLBuilderExtensions.cs [hunk 1]
```diff
@@ -1200,6 +1200,15 @@ public static IGraphQLBuilder AddExecutionStrategy<TExecutionStrategy>(this IGra
     /// </summary>
     /// <remarks>
     /// When applicable, place after calls to UseAutomaticPersistedQueries to ensure that the query document is recorded properly.
+    /// <br/>
+    /// To instruct OpenTelemetry SDK to collect the traces produced by GraphQL.NET register the
+    /// '<see cref="GraphQLTelemetryProvider.SourceName"/>' source name with the TracerProviderBuilder.
+    /// <code>
+    /// services
+    ///     .AddOpenTelemetry()
+    ///     .WithTracing(tracing => tracing
```
Comment (Shane32) [inline src/GraphQL/Extensions/GraphQLBuilderExtensions.cs:1209]:
```suggestion
    ///     .WithTracing(tracing =&gt; tracing
```
??

**Review by Shane32 — APPROVED** [review]
