### PR TITLE
Allow converting scalar values to/from null, don't call ValueConverter, fix list handling of errors

### LINKED ISSUE #2333: Add null support to ScalarGraphType
I’m thinking that we should issue another PR immediately after this one to have scalars handle null values. People have asked for it before, and with all the cleanup we have done for v4, it will be very easy to implement (finally!).

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/graphql-dotnet/pull/2321#discussion_r584180364_

### PR DESCRIPTION
**Pull request by Shane32**
Fixes #2333 and replaces #2320

* [x] Update calls to ParseValue
* [x] Update calls to ParseLiteral
* [x] Update xml comments for all methods
* [x] No change to calls to CanParseLiteral / CanParseValue
* [x] Update calls to Serialize
* [x] Update calls to ToAST
* [x] Fix SchemaBuilder's handling of default values
* [x] Confirm new behavior: Scalar numeric types do not allow strings
* [x] Confirm new behavior: Scalar integer numeric types do not allow floating-point values
* [x] Confirm new behavior: Enumeration types do not allow strings
* [x] Confirm new behavior: String type does not allow non-string values
* [x] Confirm new behavior: Id type allows any numeric or string type of incoming value; serialize always returns string
* [x] Add more tests

Scalars:
* [x] All redone

~~Note: this PR does not include removing the calls to `ValueConverter`. See #2320~~

### CODE REVIEW

**Comment by Shane32** [comment]
@sungam3r Please review xml comments within `ScalarGraphType.cs`.  It will explain the suggested changes that I'll be making.

File: src/GraphQL/Types/Scalars/BooleanGraphType.cs [hunk 1]
```diff
@@ -9,15 +9,26 @@ namespace GraphQL.Types
     public class BooleanGraphType : ScalarGraphType
     {
         /// <inheritdoc/>
-        public override object ParseLiteral(IValue value) => ((value as BooleanValue)?.Value).Boxed();
+        public override object ParseLiteral(IValue value) => value switch
+        {
+            BooleanValue b => b.Value.Boxed(),
+            NullValue _ => null,
+            _ => null
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/BooleanGraphType.cs:16]: Why not `ThrowLiteralConversionError` ?

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 2]
```diff
@@ -152,5 +165,25 @@ public virtual IValue ToAST(object value)
                 return null;
             }
         }
+
+        protected internal object ThrowLiteralConversionError(IValue input)
+        {
+            throw new ArgumentException($"Unable to convert '{input}' to '{Name}'");
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:171]:
```suggestion
            throw new ArgumentException($"Unable to convert '{input}' from AST representation to '{Name}'");
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 3]
```diff
@@ -58,8 +65,12 @@ public abstract class ScalarGraphType : GraphType
         /// server-side representation.
         /// <br/><br/>
         /// This method can be overridden to validate input values without directly getting those values, i.e. without boxing.
+        /// <br/><br/>
+        /// This method must not be called for <see cref="NullValue"/> nodes as it is assumed that all scalars handle
+        /// <see cref="NullValue"/>. It is not necessary to provide a <see langword="true"/> response for
+        /// <see cref="NullValue"/> nodes. Use a non-null graph type to indicate that a scalar value does not support null.
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:71]:
```suggestion
        /// <see cref="NullValue"/> nodes. Use a non-null graph type to indicate that a scalar value does not support <see langword="null"/>.
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 4]
```diff
@@ -81,6 +92,10 @@ public virtual bool CanParseLiteral(IValue value)
         /// always be expressed in GraphQL query syntax, variable format is transport-specific (usually JSON).
         /// <br/><br/>
         /// This method can be overridden to validate input values without directly getting those values, i.e. without boxing.
+        /// <br/><br/>
+        /// This method must not be called for <see langword="null"/> values as it is assumed that all scalars handle
+        /// <see langword="null"/>. It is not necessary to provide a <see langword="true"/> response for
+        /// <see langword="null"/> values. Use a non-null graph type to indicate that a scalar value does not support null.
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:98]:
```suggestion
        /// <see langword="null"/> values. Use a non-null graph type to indicate that a scalar value does not support <see langword="null"/>.
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 5]
```diff
@@ -152,5 +165,25 @@ public virtual IValue ToAST(object value)
...
+        {
+            throw new InvalidOperationException($"Unable to convert '{value}' of the scalar type '{Name}' to an AST representation.");
+        }
+
+        protected internal object ThrowValueConversionError(object value)
+        {
+            throw new ArgumentException($"Unable to convert '{value}' to '{Name}'");
+        }
+
+        protected internal object ThrowSerializationError(object value)
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:184]: Used only fro enums?

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 6]
```diff
@@ -152,5 +165,25 @@ public virtual IValue ToAST(object value)
...
+        {
+            throw new InvalidOperationException($"Unable to serialize '{value}' to '{Name}'.");
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:186]:
```suggestion
            throw new InvalidOperationException($"Unable to serialize '{value}' to the scalar type '{Name}'.");
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 7]
```diff
@@ -152,5 +165,25 @@ public virtual IValue ToAST(object value)
...
+        }
+
+        protected internal IValue ThrowASTConversionError(object value)
+        {
+            throw new InvalidOperationException($"Unable to convert '{value}' of the scalar type '{Name}' to an AST representation.");
+        }
+
+        protected internal object ThrowValueConversionError(object value)
+        {
+            throw new ArgumentException($"Unable to convert '{value}' to '{Name}'");
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:181]:
```suggestion
            throw new ArgumentException($"Unable to convert '{value}' to the scalar type '{Name}'");
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 8]
```diff
@@ -152,5 +165,25 @@ public virtual IValue ToAST(object value)
...
         }
+
+        protected internal object ThrowLiteralConversionError(IValue input)
+        {
+            throw new ArgumentException($"Unable to convert '{input}' to '{Name}'");
+        }
+
+        protected internal IValue ThrowASTConversionError(object value)
+        {
+            throw new InvalidOperationException($"Unable to convert '{value}' of the scalar type '{Name}' to an AST representation.");
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:176]:
```suggestion
            throw new InvalidOperationException($"Unable to convert '{value}' to an AST representation for the scalar type '{Name}'.");
```

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:176]: I tried to make the messages similar for all four methods.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 9]
```diff
@@ -81,6 +92,10 @@ public virtual bool CanParseLiteral(IValue value)
         /// always be expressed in GraphQL query syntax, variable format is transport-specific (usually JSON).
         /// <br/><br/>
         /// This method can be overridden to validate input values without directly getting those values, i.e. without boxing.
+        /// <br/><br/>
+        /// This method must not be called for <see langword="null"/> values as it is assumed that all scalars handle
+        /// <see langword="null"/>. It is not necessary to provide a <see langword="true"/> response for
+        /// <see langword="null"/> values. Use a non-null graph type to indicate that a scalar value does not support null.
         /// </summary>
         /// <param name="value">Runtime object from variables. Must not be <see langword="null"/>.</param>
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: изображение

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: The same question about ParseLiteral/CanParseLiteral.

File: src/GraphQL/Validation/ValidationContext.cs [hunk 10]
```diff
@@ -318,21 +318,14 @@ object ParseValue(IGraphType type, VariableDefinition variableDef, VariableName
...
             {
-                if (value == null)
-                    return null;
-
-                object ret;
-
                 try
                 {
-                    ret = scalarGraphType.ParseValue(value);
+                    return scalarGraphType.ParseValue(value);
```
Comment (sungam3r) [inline src/GraphQL/Validation/ValidationContext.cs:323]: So, it's absolutely OK now:
1. Return `null` as parsed scalar result.
2. Accept `null` and return _some_ parsed result not necessarily equal to `null`.

If so, this must be described in detail in the documentation.

File: src/GraphQL/Types/Scalars/BooleanGraphType.cs (hunk 1 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/BooleanGraphType.cs:16]: Bug; throwing is necessary.  I will be writing tests also.  Good to have you reviewing everything also to help catch these things!

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 2 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:171]: 👍 

Once I can get existing tests to pass again, then I'll commit the revised exception messages.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 5 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:184]: We will see.  Right now, `ThrowValueConversionError` isn't used at all!  But that will change once `ValueConverter` is removed. 
 And since the default implementation of `Serialize` calls `ParseValue`, we may get exception messages intended for `ParseValue` be returned during a failed call to `Serialize`.  Something we need to think about during the review.  Still a WIP just now.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 6 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:186]: 👍

Once I can get existing tests to pass again, then I'll commit the revised exception messages.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 7 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:181]: 👍

Once I can get existing tests to pass again, then I'll commit the revised exception messages.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 8 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:176]: 👍

Once I can get existing tests to pass again, then I'll commit the revised exception messages.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 9 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: I'm not sure what the question is.  There already are comments in there for those members.

image

File: src/GraphQL/Validation/ValidationContext.cs (hunk 10 above)
Comment (Shane32) [reply src/GraphQL/Validation/ValidationContext.cs:323]: Yes, we will need a significant change to the documentation for scalars.  We could perhaps provide two samples: one where empty strings internally are coerced to null externally, and one where 0 values internally are converted to/from null external values.

File: src/GraphQL/Types/Scalars/BooleanGraphType.cs (hunk 1 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/BooleanGraphType.cs:16]: > I will be writing tests also

Tests will save us.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 9 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: изображение
 
`Must not` vs `may be` on `TryParseValue` / `ParseValue`.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: It is correct.  `ParseLiteral(null)` is illegal.  `ParseLiteral(new NullValue())` is legal and required to be implemented.

`ParseValue` accepts an object, not an `IValue`.  So `ParseValue(null)` is legal and required to be implemented.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: If we used NRT annotations, the definitions would be:

```cs
object? ParseLiteral(IValue value);
object? ParseValue(object? value);
```

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: I suggest reading the comments again without the diff.  It should be pretty clear.  If not, I'd be happy to revise it.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: image
image
image
image
image

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: Let's talk only about ParseValue/CanParseValue.

> So ParseValue(null) is legal and required to be implemented.

OK. I see it. But I also see that comment above ` public virtual bool CanParseValue(object value)` for `value` arg:
>  /// \<param name="value">Runtime object from variables. Must not be \<see langword="null"/>.</param>

So... I conclude that
1. `ParseValue(null)` is legal
2. `CanParseValue(null)` is illegal.

Why??

**Comment by Shane32** [comment]
@sungam3r Sorry this is another whopper of a PR.  Since I was rewriting most of the scalars, I also made the changes necessary for #2320 .

A number of old tests broke, due to the fact that the scalars will not perform conversions automatically anymore.  Specifically, the numeric scalars will not accept a string when serializing, and do not accept a string within `ParseValue`.  They also don't convert floating-point values to integer values.

This raises a point of concern: what data type does `Newtonsoft.Json` deserialize large integer values to?  If it deserializes large integers to a `double`, then this breaks existing code.  I have not tested yet.  We can see that for `System.Text.Json`, the `ObjectDictionaryConverter` will return a `double` if it is equally as accurate as a `BigInteger` representation.  So that would need to be fixed.

It might be better to allow integer scalars to parse floating-point variables values, coercing them to integers.  Agree?  And perhaps they should not parse floating-point literals?

I also modified the schema builder to use `ParseLiteral` to convert a supplied default into a internal variable.  This works well -- for example, now incorrect enum values are caught during the schema build phase rather than during validation.  However, it doesn't always work because the graph type for a default value can be (at that point) a `GraphQLTypeReference`.  Can you help me here?  I'm thinking maybe we can temporarily store the default object (the AST node) within the `field.DefaultValue` property, and then once the schema has finished building (but before exiting `.Build()`), run a walker against the built schema to convert `DefaultValue` properties appropriately.  This only works if the `GraphQLTypeReference`s are resolved before schema initialization.  Are they?  Would this work?  I feel like this is on the right track, but I have not spent enough time to work out the details.

A few other notes:
- We need to review what exceptions are returned.
- I need to revise test names, if applicable
- Still have not yet rewritten the execution strategy to pass null values through `Serialize`, and then validate non-nullability afterwards.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 8 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs]: Code was unused when done (since ToAST default implementation was sufficient in every case), so I removed the method.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 9 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:100]: I understand your point of view.  Makes sense.  `CanParseLiteral` has same situation - should not be calling it for `NullValue`.  I just need to add conditions to all `CanParseValue` and `CanParseLiteral` methods to handle `null` and `NullValue` respectively.  I'll push the necessary changes.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:97]: Comments and code and tests have been revised.

File: src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs [hunk 11]
```diff
@@ -798,7 +798,7 @@ public void prints_enum_default_args()
                 Arguments = new QueryArguments(new QueryArgument<RgbEnum>
                 {
                     Name = "color",
-                    DefaultValue = "RED"
+                    DefaultValue = 0 // 0 = red --- must be internal representation of enumeration value or validation will fail
                 }),
```
Comment (Shane32) [inline src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs:802]: Internal representations of enum values must be respected for `DefaultValue`.  So setting it to "RED" is invalid because that is an external representation, not an internal representation.  I would almost say this was a bug, as it certainly can cause hidden problems in users' code.

File: src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs [hunk 12]
```diff
@@ -193,6 +193,7 @@ public void configures_schema_from_schema_type_and_directives()
         [Fact]
         public void builds_type_with_arguments()
         {
+            // TEST BROKEN: CoerceValue for default value cannot execute on a GraphQLTypeReference graph type
```
Comment (Shane32) [inline src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs:196]: Needs to be fixed

File: src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs [hunk 13]
```diff
@@ -286,6 +287,7 @@ scalar CustomScalar
         [Fact]
         public void references_other_types()
         {
+            // TEST BROKEN: CoerceValue for default value cannot execute on a GraphQLTypeReference graph type
```
Comment (Shane32) [inline src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs:290]: Needs to be fixed.

File: src/GraphQL.Tests/Utilities/SchemaVisitorTests.cs [hunk 14]
```diff
@@ -64,6 +64,7 @@ public class TestTypeForUnion
         [Fact]
         public void can_create_custom_directive_for_all_locations()
         {
+            // TEST BROKEN: CoerceValue for default value cannot execute on a GraphQLTypeReference graph type
```
Comment (Shane32) [inline src/GraphQL.Tests/Utilities/SchemaVisitorTests.cs:67]: Needs to be fixed.  All other tests pass except these 3.

File: src/GraphQL/Types/Scalars/DateTimeGraphType.cs [hunk 15]
```diff
@@ -20,13 +21,39 @@ public DateTimeGraphType()
...
+            }
+
+            throw new FormatException($"Could not parse date. Expected ISO-8601 format. Value: {stringValue}");
+        }
 
         /// <inheritdoc/>
-        public override IValue ToAST(object value) => new StringValue(((DateTime)value).ToString("O")); // "O" is the proper ISO 8601 format required
+        public override object Serialize(object value) => value switch
+        {
+            DateTime d => d.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK", DateTimeFormatInfo.InvariantInfo), // ISO-8601 format (without unnecessary decimal places, allowed by ISO-8601)
```
Comment (Shane32) [inline src/GraphQL/Types/Scalars/DateTimeGraphType.cs:54]: The ISO-8601 serialization format is now specified in code, rather than relying on System.Text.Json to provide the conversion.  The format has not changed and tests that rely on this exact format still pass.  Note that the "O" format is similar but always prints the fractional parts of the second, which is not required by ISO-8601.

File: src/GraphQL/Types/Scalars/DateTimeOffsetGraphType.cs [hunk 16]
```diff
@@ -20,13 +21,39 @@ public DateTimeOffsetGraphType()
...
+            DateTimeOffset _ => value,
+            string s => ParseDate(s),
+            null => null,
+            _ => ThrowValueConversionError(value)
+        };
+
+        private static DateTimeOffset ParseDate(string stringValue)
+        {
+            // ISO-8601 format
+            if (DateTimeOffset.TryParseExact(stringValue, "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK", DateTimeFormatInfo.InvariantInfo, DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal, out var date))
```
Comment (Shane32) [inline src/GraphQL/Types/Scalars/DateTimeOffsetGraphType.cs:43]: Also note that we now require a ISO-8601 compliant date format to deserialize the data, rather than simply TryParse

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs [hunk 17]
```diff
@@ -62,39 +62,48 @@ public void AddValue(EnumValueDefinition value)
...
-            var valueString = value.ToString(); //TODO: find only by value?
-            var foundByName = Values.FindByName(valueString);
-            if (foundByName != null)
-            {
-                return foundByName.Name;
-            }
+            EnumValue enumValue => Values.FindByName(enumValue.Name)?.Value ?? ThrowLiteralConversionError(value),
+            NullValue _ => null,
+            _ => ThrowLiteralConversionError(value)
+        };
```
Comment (Shane32) [inline src/GraphQL/Types/Scalars/EnumerationGraphType.cs:70]: We even had a TODO note in here to remove searching by name for Serialize.  Now fixed.

File: src/GraphQL/Types/Scalars/IdGraphType.cs [hunk 18]
```diff
@@ -23,31 +23,39 @@ public IdGraphType()
...
         };
 
         /// <inheritdoc/>
-        public override IValue ToAST(object value) => new StringValue(value.ToString());
+        public override object ParseValue(object value) => value switch
+        {
+            int _ => value,
+            long _ => value,
+            _ => value?.ToString().Trim(' ', '"')
+        };
```
Comment (Shane32) [inline src/GraphQL/Types/Scalars/IdGraphType.cs:53]: So.... when is `int` / `long` preserved, and when is it converted to strings?  Always convert to string and trim?  Why trim?  Why convert to string?  Not sure here.

File: src/GraphQL/Types/Scalars/StringGraphType.cs [hunk 19]
```diff
@@ -9,15 +9,25 @@ namespace GraphQL.Types
...
+        public override bool CanParseLiteral(IValue value) => value is StringValue || value is NullValue;
 
         /// <inheritdoc/>
-        public override bool CanParseLiteral(IValue value) => value is StringValue;
+        public override object ParseValue(object value) => value switch
+        {
+            string _ => value,
+            null => null,
+            _ => ThrowValueConversionError(value)
+        };
```
Comment (Shane32) [inline src/GraphQL/Types/Scalars/StringGraphType.cs:28]: Note that Serialize calls ParseValue.  So strings returned from resolvers must now be strings for StringGraphType

File: src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs (hunk 12 above)
Comment (Shane32) [reply src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs]: Fixed.

File: src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs (hunk 13 above)
Comment (Shane32) [reply src/GraphQL.Tests/Utilities/SchemaBuilderTests.cs]: Fixed.

File: src/GraphQL.Tests/Utilities/SchemaVisitorTests.cs (hunk 14 above)
Comment (Shane32) [reply src/GraphQL.Tests/Utilities/SchemaVisitorTests.cs]: Fixed.

File: src/GraphQL/Utilities/SchemaBuilder.cs [hunk 20]
```diff
@@ -308,13 +308,14 @@ protected virtual FieldType ToFieldType(string parentTypeName, GraphQLInputValue
...
+            var graphType = ToGraphType(inputDef.Type);
             var field = new FieldType
             {
                 Name = name,
                 Description = fieldConfig.Description ?? inputDef.Comment?.Text.ToString(),
                 DeprecationReason = fieldConfig.DeprecationReason,
-                ResolvedType = ToGraphType(inputDef.Type),
-                DefaultValue = inputDef.DefaultValue.ToValue()
+                ResolvedType = graphType,
+                DefaultValue = inputDef.DefaultValue == null ? null : Execution.ExecutionHelper.CoerceValue(graphType, Language.CoreToVanillaConverter.Value(inputDef.DefaultValue)).Value
```
[the remark this answers is not in the document]
Comment (Shane32) [reply src/GraphQL/Utilities/SchemaBuilder.cs]: Update: Now this stores the AST representation within `DefaultValue` until the schema validation visitor can replace the values by calling the scalar type's `ParseLiteral` method.

File: src/GraphQL/Utilities/SchemaBuilder.cs [hunk 21]
```diff
@@ -450,11 +451,12 @@ private EnumValueDefinition ToEnumValue(GraphQLEnumValueDefinition valDef)
...
         protected virtual QueryArgument ToArgument(GraphQLInputValueDefinition inputDef)
         {
-            return new QueryArgument(ToGraphType(inputDef.Type))
+            var graphType = ToGraphType(inputDef.Type);
+            return new QueryArgument(graphType)
             {
                 Name = (string)inputDef.Name.Value,
-                DefaultValue = inputDef.DefaultValue.ToValue(),
-                ResolvedType = ToGraphType(inputDef.Type),
+                DefaultValue = inputDef.DefaultValue == null ? null : Execution.ExecutionHelper.CoerceValue(graphType, Language.CoreToVanillaConverter.Value(inputDef.DefaultValue)).Value,
```
[the remark this answers is not in the document]
Comment (Shane32) [reply src/GraphQL/Utilities/SchemaBuilder.cs]: See above.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 22]
```diff
@@ -0,0 +1,604 @@
+using System;
+using System.Numerics;
+using GraphQL.Language.AST;
+using GraphQL.Types;
+using Shouldly;
+using Xunit;
+
+namespace GraphQL.Tests.Types
+{
+    public class AllScalarGraphTypeTests
```
[the remark this answers is not in the document]
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:10]: Just FYI, this new class comprises of 248 tests.  Many have loops within them to check all different possible type conversions allowed, plus verifying `CanParse` at the same time.  There could easily be 1000+ method checks here.  Hopefully this is pretty comprehensive coverage.  Waiting to see the codecov report!

**Comment by sungam3r** [comment]
> It might be better to allow integer scalars to parse floating-point variables values, coercing them to integers. Agree? And perhaps they should not parse floating-point literals?

Seems so.

File: src/GraphQL.Tests/Bugs/ScalarsInputTest.cs [hunk 23]
```diff
@@ -182,11 +182,11 @@ public void Should_Not_Accept_String_As_Long_In_Literal()
...
         // TODO: rework to throw exception
         [Fact]
-        public void Should_Accept_String_As_Long_In_Variable()
+        public void Should_Not_Accept_String_As_Long_In_Variable()
         {
             var query = @"mutation AAA($val : Long!) { long(number: $val) }";
             var expected = @"{ ""long"": 100 }";
-            AssertQuerySuccess(query, expected, @"{ ""val"": ""100"" }".ToInputs(), null);
+            AssertQueryWithErrors(query, expected, @"{ ""val"": ""100"" }".ToInputs(), expectedErrorCount: 1, executed: false);
         }
```
[the remark this answers is not in the document]
Comment (sungam3r) [reply src/GraphQL.Tests/Bugs/ScalarsInputTest.cs:190]: More recently, I seem to have fixed this for literals.

File: src/GraphQL.Tests/Execution/VariablesTests.cs [hunk 24]
```diff
@@ -123,12 +123,7 @@ public TestType()
                 arguments: new QueryArguments(
                     new QueryArgument<IntGraphType> { Name = "input" }
                 ),
-                resolve: context =>
-                {
-                    var val = context.GetArgument<int>("input");
-                    var result = JsonSerializer.Serialize(val);
-                    return result;
-                });
+                resolve: context => context.GetArgument<int>("input"));
```
[the remark this answers is not in the document]
Comment (sungam3r) [reply src/GraphQL.Tests/Execution/VariablesTests.cs:126]: I have seen. I've already fixed this for literals.

File: src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs (hunk 11 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs:802]: OK. Can it be `Color.Red` ?

File: src/GraphQL/Types/Scalars/DateTimeGraphType.cs (hunk 15 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/DateTimeGraphType.cs:54]: Please add comments here about differences with 'O' format.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 17 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:70]: Yes, I suspected for a long time that something was wrong.

File: src/GraphQL/Types/Scalars/IdGraphType.cs (hunk 18 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/IdGraphType.cs:53]: > The ID scalar graph type represents a **string** identifier, not intended to be human-readable. 
\+
> When expected as an **input** type, any string or integer input value will be accepted as an ID.

See http://spec.graphql.org/draft/#sec-ID

So ...
> when is it converted to strings?

When serializing into response.

> Why convert to string?

Because spec requires it.

>  Why trim?

It seems to me that this is some kind of design flaw. Spec says nothing about trimming. Try run tests without trim.

File: src/GraphQL/Types/Scalars/IntGraphType.cs [hunk 25]
```diff
@@ -12,25 +12,56 @@ public class IntGraphType : ScalarGraphType
...
+        };
+
+        private static readonly object _boxedNeg1 = -1;
+        private static readonly object _boxed0 = 0;
+        private static readonly object _boxed1 = 1;
+        private static readonly object _boxed2 = 2;
+        private static readonly object _boxed3 = 3;
+        private static readonly object _boxed4 = 4;
+        private static readonly object _boxed5 = 5;
+        private static object BoxValue(int value) => value switch
```
[the remark this answers is not in the document]
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/IntGraphType.cs:55]: From time to time I thought about doing this, but gave up this thought. This looks a little odd and adds processing time. We need to look at the problem more broadly - #2237 
изображение

File: src/GraphQL/Types/Scalars/StringGraphType.cs (hunk 19 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/StringGraphType.cs:28]: OK. It should be clearly stated in the documentation that in version 4 scalars became stricter on the supported types. They practically stopped doing any value conversions.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 22 above)
[the remark this answers is not in the document]
Comment (sungam3r) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:10]: ScalarGraphTypeTests

File: src/GraphQL.Tests/Types/SByteGraphTypeTests.cs [hunk 26]
```diff
@@ -12,26 +12,26 @@ public void Coerces_given_inputs_to_null()
...
+        [InlineData("-129")]
         [InlineData("abc")]
         [InlineData("-999999.99")]
-        public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
-            AssertException<FormatException>(input);
+        public void Coerces_strings_to_argument_exception(object input) =>
+            AssertException<ArgumentException>(input);
 
         [Fact]
         public void Coerces_double_to_invalid_operation_exception()
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/SByteGraphTypeTests.cs:31]:
```suggestion
        public void Coerces_double_to_argument_exception()
```

Comment (sungam3r) [reply src/GraphQL.Tests/Types/SByteGraphTypeTests.cs:31]: Or change throwed exception to `InvalidOperationException`.

File: src/GraphQL.Tests/Types/ShortGraphTypeTests.cs [hunk 27]
```diff
@@ -14,27 +14,27 @@ public void Coerces_given_inputs_to_null()
...
         [InlineData("-999999.99")]
+        [InlineData("32767")]
+        [InlineData("-32768")]
+        [InlineData("0")]
         public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
-            AssertException<FormatException>(input);
+            AssertException<ArgumentException>(input);
 
         [Fact]
         public void Coerces_double_to_invalid_operation_exception()
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/ShortGraphTypeTests.cs:32]: Change test name of exception type.

Comment (sungam3r) [reply src/GraphQL.Tests/Types/ShortGraphTypeTests.cs:32]: The same for other tests.

File: src/GraphQL.Tests/Types/UShortGraphTypeTests.cs [hunk 28]
```diff
@@ -15,25 +15,25 @@ public void Coerces_given_inputs_to_null()
...
+        [InlineData("123")]
+        [InlineData("65535")]
         public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
-            AssertException<FormatException>(input);
+            AssertException<ArgumentException>(input);
 
         [Fact]
         public void Coerces_double_to_invalid_operation_exception()
-            => AssertException<InvalidOperationException>(999999.99);
+            => AssertException<ArgumentException>(999999.99);
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/UShortGraphTypeTests.cs:34]: All such tests can be merged with the previous test if the same type of exception is thrown.

File: src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs (hunk 11 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs:802]: `Color.Red` is more native for me even than `0`. Need a test.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 29]
```diff
@@ -18,13 +19,15 @@ public abstract class ScalarGraphType : GraphType
...
+        /// This method must handle a value of <see langword="null"/>.
         /// </summary>
-        /// <param name="value">Resolved value. Must not be <see langword="null"/>.</param>
+        /// <param name="value">Resolved value. May be <see langword="null"/>.</param>
         /// <returns>
         /// The returned value of a the result coercion is part of the overall execution result.
         /// Normally this value is a primitive value like String or Integer to make it easy for
         /// the serialization layer. For complex types like a Date or Money Scalar this involves
-        /// formatting the value. Returning <see langword="null"/> indicates a failed conversion.
+        /// formatting the value. Returning <see langword="null"/> is valid for nullable types.
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]: > is valid for **nullable** types

What do you mean? Nullable CLR types like `string` ? Now I see that each numeric scalar throws from `ParseValue` for `null`. OK. `String` scalar does not throw. OK. But `Guid` scalar ( not nullable CLR type) again does not throw. 😕 ?

File: src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs (hunk 11 above)
Comment (Shane32) [reply src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs:802]: There is an overabundance of tests for enums located in `Bug1699InvalidEnum`.  We explicitly test for both - see the `Simple_Enum` and `Enum_From_Number` tests.

However, in this particular test, the enumeration is created by the schema builder, so there is no native .NET enum type.

File: src/GraphQL/Types/Scalars/DateTimeGraphType.cs (hunk 15 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/DateTimeGraphType.cs:54]: Done

File: src/GraphQL/Types/Scalars/IdGraphType.cs (hunk 18 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/IdGraphType.cs:53]: Right; I understand that it should serialize to strings when serializing values.  I mean, when being parsed, why, or why not, convert to strings?  Perhaps we should always convert literals and values to strings, or perhaps never (and let GetArgument handle this).  Or perhaps we never convert values to strings, allowing any type (float, decimal, sbyte, whatever).

I'll try removing Trim.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/IdGraphType.cs:53]: breaks these tests:
```cs
        [Fact]
        public void parse_value_quoted_string_to_identifier()
        {
            _type.ParseValue("\"12345\"").ShouldBe("12345");
        }

        [Fact]
        public void parse_literal_string_value_quoted_string_to_identifier()
        {
            _type.ParseLiteral(new StringValue("\"12345\"")).ShouldBe("12345");
        }
```
(which still don't seem to make sense to me)

File: src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs (hunk 11 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Utilities/SchemaPrinterTests.cs:802]: OK

File: src/GraphQL/Types/Scalars/IdGraphType.cs (hunk 18 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/IdGraphType.cs:53]: I'm going to remove these two tests as well.  Lmk if not

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/IdGraphType.cs:53]: >  I mean, when being parsed, why, or why not, convert to strings? Perhaps we should always convert literals and values to strings, or perhaps never (and let GetArgument handle this). 

I think that `ID` as a input type _can_ be used in different ways depending on the type of the variable/literal. Type of input   is an additional source of information besides the actual value. Imagine two options: `"123"` and `123`

```graphql
query {
  user(id: ID!)
}
```

And imagine this `User` CLR type:
```csharp
public class User
{
   public int InternalID { get; set; }
   public string ExternalID { get; set; }
}
```

Resolver:
```csharp
context => {
  if (context.Arguments["id"] is int id)
  {
     // search by internal id
  }
  else if (context.Arguments["id"] is string s)
  {
    // search by external id
  }
}
```

> I'm going to remove these two tests as well. Lmk if not

OK. Even if we did not understand the purpose of `Trim`, then after the release of v4 we will surely receive some feedback. If necessary, we can return the old behavior. Also ping @joemcbride for advice.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/IdGraphType.cs:53]: We can always add `Trim` back in without a breaking change.  Similar with other restrictions we have made for scalars.  Also I think we should most definitely provide a sample of overriding a built-in scalar within the migration documentation.

File: src/GraphQL/Types/Scalars/IntGraphType.cs (hunk 25 above)
[the remark this answers is not in the document]
Comment (Shane32) [reply src/GraphQL/Types/Scalars/IntGraphType.cs:55]: I've seen this before; I think it's generally done the way I did it -- a very small (5-10) number of literals are pre-boxed.  I could be wrong.

I only added this code for `IntGraphType` as it should be the most common numeric type.  However, it's only useful for input literals so maybe it's not that valuable.  Keep or remove?  I did add tests for this, by the way.

[the remark this answers is not in the document]
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/IntGraphType.cs:55]: > I've seen this before

Maybe for index in response path? There it is more useful because the index increases monotonically from 0. Therefore, the "boxed cache" hit rate is high. In the case of scalars, we work with arbitrary values and we have no idea what values are used more often. I would remove this code.

**Comment by Shane32** [comment]
@sungam3r What do you think about the exception types that these methods throw?  Let's decide that, then I can revise the name of the old tests, etc.

```cs
        internal object ThrowLiteralConversionError(IValue input)
        {
            throw new ArgumentException($"Unable to convert '{input}' literal from AST representation to the scalar type '{Name}'");
        }

        // this is often called for serialization errors, since Serialize calls ParseValue by default
        // also may be called for serialization errors during ToAST, since ToAST calls Serialize by default, which by default calls ParseValue
        internal object ThrowValueConversionError(object value)
        {
            throw new ArgumentException($"Unable to convert '{value}' to the scalar type '{Name}'");
        }

        // also may be called for serialization errors during ToAST, since ToAST calls Serialize by default
        internal object ThrowSerializationError(object value)
        {
            throw new InvalidOperationException($"Unable to serialize '{value}' to the scalar type '{Name}'.");
        }
```

File: src/GraphQL.Tests/Bugs/Bug1773.cs [hunk 30]
```diff
@@ -60,31 +60,31 @@ public void list_throws_for_invalid_type()
...
-                new FormatException("Input string was not in a correct format."), localizedMessage: "Входная строка имела неверный формат.");
+                new ArgumentException("Unable to convert 'test' to the scalar type 'Int'"), localizedMessage: "Входная строка имела неверный формат.");
         }
 
         [Fact]
         public void list_throws_for_invalid_type_when_conversion_returns_null()
         {
             // TODO: does not yet fully meet spec (does not return members of lists that are able to be serialized, with nulls and individual errors for unserializable values)
             AssertQueryWithError("{testListInvalidType2}", "{\"testListInvalidType2\": null}", "Error trying to resolve field 'testListInvalidType2'.", 1, 2, new[] { "testListInvalidType2" },
-                new InvalidOperationException("Unable to serialize 'test' to 'Bug1773Enum' for list index 0."));
```
Comment (sungam3r) [inline src/GraphQL.Tests/Bugs/Bug1773.cs:71]: Some context information was lost - `for list index X`. See `ExecutionStrategy.SetArrayItemNode`.
That said, that's OK, as every error has `Path` property with the same information. I wanted to check this and run this test. To my surprise, I did not see the `0` index in `Path`, only parent `testListInvalidType2` field. Then I look into execution strategy. 
изображение

Now I think why we handle arrays in such way? If array supports null values then we must set item to `null` and go on. Now the single error from `SetArrayItemNode` prevents from calculatin the whole parent array node. So I'm sure this is a bug. `testListInvalidType2` should be `[null]`, not `null`. Also need to add another test for non-nullable items in array. Thoughts?


@Shane32 I will fix this if you agree that I understood the situation correctly.

Comment (Shane32) [reply src/GraphQL.Tests/Bugs/Bug1773.cs:71]: I agree

**Comment by Shane32** [comment]
> @sungam3r What do you think about the exception types that these methods throw? Let's decide that, then I can revise the name of the old tests, etc.
> 
> ```cs
>         internal object ThrowLiteralConversionError(IValue input)
>         {
>             throw new ArgumentException($"Unable to convert '{input}' literal from AST representation to the scalar type '{Name}'");
>         }
> 
>         // this is often called for serialization errors, since Serialize calls ParseValue by default
>         // also may be called for serialization errors during ToAST, since ToAST calls Serialize by default, which by default calls ParseValue
>         internal object ThrowValueConversionError(object value)
>         {
>             throw new ArgumentException($"Unable to convert '{value}' to the scalar type '{Name}'");
>         }
> 
>         // also may be called for serialization errors during ToAST, since ToAST calls Serialize by default
>         internal object ThrowSerializationError(object value)
>         {
>             throw new InvalidOperationException($"Unable to serialize '{value}' to the scalar type '{Name}'.");
>         }
> ```

Changed all three to `InvalidOperationException`.

File: src/GraphQL/Types/Scalars/IntGraphType.cs (hunk 25 above)
[the remark this answers is not in the document]
Comment (Shane32) [reply src/GraphQL/Types/Scalars/IntGraphType.cs]: Done

**Comment by Shane32** [comment]
@sungam3r Where we at now?  Are the new semantics agreed upon?  I have not yet updated the names of old tests, and similar, and I have not updated the calls to `Serialize` and/or `ToAST` to handle null values, or added documentation.  I will probably not modify `Serialize` until #2348 is done, if you're doing that today.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 29 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]: What about Guid?

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]: `GuidGraphType.ParseValue(null)` should (and does) return `null`.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]: `GuidGraphType.ParseLiteral(new NullValue())` should (and does) return `null`.
`GuidGraphType.Serialize(null)` should (and does) return `null`.

**Comment by sungam3r** [comment]
I will be able to return to work on the project after 4 hours. 18/49 files viewed.

**Comment by Shane32** [comment]
Sounds good.  I have work to do also.

**Comment by Shane32** [comment]
Changes from #2320 were merged in.

**Comment by sungam3r** [comment]
>  What do you think about the exception types that these methods throw? Let's decide that, then I can revise the name of the old tests, etc.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 29 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]: > Now I see that each numeric scalar throws from ParseValue for null

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]: Yes.

File: src/GraphQL.Tests/Bugs/Bug1205VeryLongInt.cs [hunk 31]
```diff
@@ -3,6 +3,7 @@
 using GraphQL.Types;
 using GraphQL.Validation;
 using GraphQL.Validation.Errors;
+using Shouldly;
```
Comment (Shane32) [inline src/GraphQL.Tests/Bugs/Bug1205VeryLongInt.cs:6]:
```suggestion
```

File: src/GraphQL.Tests/Types/ByteGraphTypeTests.cs [hunk 32]
```diff
@@ -12,27 +12,26 @@ public void Coerces_given_inputs_to_null()
...
         [InlineData("-999999.99")]
-        public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
-            AssertException<FormatException>(input);
-
-        [Fact]
-        public void Coerces_double_to_invalid_operation_exception()
-            => AssertException<InvalidOperationException>(999999.99);
+        [InlineData("12")]
+        [InlineData("125")]
+        public void Coerces_given_inputs_to_argument_exception(object input) =>
```
Comment (Shane32) [inline src/GraphQL.Tests/Types/ByteGraphTypeTests.cs:28]:
```suggestion
        public void Coerces_given_inputs_to_invalid_operation_exception(object input) =>
```

File: src/GraphQL.Tests/Types/SByteGraphTypeTests.cs [hunk 33]
```diff
@@ -12,28 +12,26 @@ public void Coerces_given_inputs_to_null()
...
+        [InlineData("-129")]
         [InlineData("abc")]
         [InlineData("-999999.99")]
-        public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
-            AssertException<FormatException>(input);
-
-        [Fact]
-        public void Coerces_double_to_invalid_operation_exception()
-            => AssertException<InvalidOperationException>(999.99);
+        public void Coerces_invalid_to_exception(object input) =>
```
Comment (Shane32) [inline src/GraphQL.Tests/Types/SByteGraphTypeTests.cs:28]:
```suggestion
        public void Coerces_to_invalid_operation_exception(object input) =>
```

File: src/GraphQL.Tests/Types/ShortGraphTypeTests.cs [hunk 34]
```diff
@@ -14,28 +14,26 @@ public void Coerces_given_inputs_to_null()
...
 
         [Theory]
+        [InlineData("999999")]
+        [InlineData("-999999")]
         [InlineData("abc")]
         [InlineData("-999999.99")]
+        [InlineData("32767")]
+        [InlineData("-32768")]
+        [InlineData("0")]
         public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
```
Comment (Shane32) [inline src/GraphQL.Tests/Types/ShortGraphTypeTests.cs:29]:
```suggestion
        public void Coerces_given_inputs_to_invalid_operation_exception(object input) =>
```

File: src/GraphQL.Tests/Types/UIntGraphTypeTests.cs [hunk 35]
```diff
@@ -15,27 +15,25 @@ public void Coerces_given_inputs_to_null()
...
 
         [Theory]
+        [InlineData("9223372036854775807")]
+        [InlineData("-9223372036854775807")]
+        [InlineData("-1")]
         [InlineData("abc")]
         [InlineData("-999999.99")]
+        [InlineData("429496")]
+        [InlineData("4294967295")]
         public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
```
Comment (Shane32) [inline src/GraphQL.Tests/Types/UIntGraphTypeTests.cs:30]:
```suggestion
        public void Coerces_given_inputs_to_invalid_operation_exception(object input) =>
```

File: src/GraphQL.Tests/Types/ULongGraphTypeTests.cs [hunk 36]
```diff
@@ -13,27 +13,25 @@ public void Coerces_given_inputs_to_null()
...
             AssertException<OverflowException>(input);
 
         [Theory]
+        [InlineData("18446744073709551616")]
+        [InlineData("-1")]
         [InlineData("abc")]
         [InlineData("-999999.99")]
+        [InlineData("1844674407")]
+        [InlineData("18446744073709551615")]
         public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
```
Comment (Shane32) [inline src/GraphQL.Tests/Types/ULongGraphTypeTests.cs:28]:
```suggestion
        public void Coerces_given_inputs_to_invalid_operation_exception(object input) =>
```

File: src/GraphQL.Tests/Types/UShortGraphTypeTests.cs [hunk 37]
```diff
@@ -15,27 +15,25 @@ public void Coerces_given_inputs_to_null()
...
 
         [Theory]
+        [InlineData("999999")]
+        [InlineData("-999999")]
+        [InlineData("-1")]
         [InlineData("abc")]
         [InlineData("-999999.99")]
+        [InlineData("123")]
+        [InlineData("65535")]
         public void Coerces_given_inputs_to_out_of_bound_exception(object input) =>
```
Comment (Shane32) [inline src/GraphQL.Tests/Types/UShortGraphTypeTests.cs:30]:
```suggestion
        public void Coerces_given_inputs_to_invalid_operation_exception(object input) =>
```

File: src/GraphQL/Utilities/SchemaBuilder.cs [hunk 38]
```diff
@@ -347,13 +347,14 @@ protected virtual FieldType ToFieldType(string parentTypeName, GraphQLInputValue
             var name = (string)inputDef.Name.Value;
             var fieldConfig = typeConfig.FieldFor(name, ServiceProvider);
 
+            var graphType = ToGraphType(inputDef.Type);
```
Comment (Shane32) [inline src/GraphQL/Utilities/SchemaBuilder.cs:350]:
```suggestion
```

File: src/GraphQL/Utilities/SchemaBuilder.cs [hunk 39]
```diff
@@ -347,13 +347,14 @@ protected virtual FieldType ToFieldType(string parentTypeName, GraphQLInputValue
...
             var field = new FieldType
             {
                 Name = name,
                 Description = fieldConfig.Description ?? inputDef.Comment?.Text.ToString(),
                 DeprecationReason = fieldConfig.DeprecationReason,
-                ResolvedType = ToGraphType(inputDef.Type),
-                DefaultValue = inputDef.DefaultValue.ToValue()
+                ResolvedType = graphType,
```
Comment (Shane32) [inline src/GraphQL/Utilities/SchemaBuilder.cs:356]:
```suggestion
                ResolvedType = ToGraphType(inputDef.Type),
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 29 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]: > Suggestions to fix this xml comment would be appreciated.

Already done?

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]: No I have not changed it yet.

**Comment by Shane32** [comment]
@sungam3r If you have any other comments, please let me know.  Otherwise I will proceed with updating the calls to `Serialize` and `ToAST` and update documentation, should be all that is necessary to finish this PR.

**Comment by sungam3r** [comment]
I switched to other PRs. I can continue review after 8-9 hours.

**Comment by Shane32** [comment]
@sungam3r While making the changes required to support serializing `null` values, I have integrated the changes for #2349, as well as the new test from that PR.

While working on it, I realized that all of the necessary checks are contained within `CompleteNode`, so `SetArrayItemNodes` simply needs to call `CompleteNode` for each item.  This ended up working perfectly, especially with the new scalar semantics.  It also reduced the amount of duplicate code and added some checks for lists of interfaces that was missing previously.  Now failures within lists always report the proper path, whether it is due to a failed conversion within a scalar graph type or if it is due to a null value set for a list of non-null values.  Null is bubbled up properly per spec when necessary.

I have also written complex testing for custom scalars, to be sure they:
- Convert from null values correctly within arguments
- Convert to null values correctly within field resolvers
- Respect non-null attributes correctly for arguments
- Respect non-null attributes correctly for field resolvers
- Works correctly within lists
- Respects non-null attributes when within lists correctly

The only thing this PR needs now is loads of documentation.  I'd rather do it in a separate PR, so I'm removing the WIP flag.  Your call.

**Comment by sungam3r** [comment]
Good. So ... ready for review?

**Comment by Shane32** [comment]
> Good. So ... ready for review?

Yes. 100% now (apart from documentation, which will take time).

**Comment by sungam3r** [comment]
Then I start. Let the documentation be in another PR.

**Comment by Shane32** [comment]
Please note that this PR does not fix (and does not intend to fix) #2253 _Stop execution as early as possible_

We can address that at a later time if desired.  (It is optional and not required to meet graphql spec anyway.)

**Comment by sungam3r** [comment]
I know.

File: src/GraphQL.Tests/Bugs/Bug1773.cs [hunk 40]
```diff
@@ -51,40 +51,45 @@ public void nonnull_list_valid()
...
+                new InvalidOperationException("Unable to serialize 'test' to the scalar type 'Bug1773Enum'."));
         }
 
         [Fact]
         public void throws_for_invalid_type()
         {
             // in this case, the conversion threw a FormatException
             AssertQueryWithError("{testInvalidType}", "{\"testInvalidType\": null}", "Error trying to resolve field 'testInvalidType'.", 1, 2, new[] { "testInvalidType" },
-                new FormatException("Input string was not in a correct format."), localizedMessage: "Входная строка имела неверный формат.");
+                new InvalidOperationException("Unable to serialize 'test' to the scalar type 'Int'."), localizedMessage: "??????? ?????? ????? ???????? ??????.");
```
Comment (Shane32) [inline src/GraphQL.Tests/Bugs/Bug1773.cs:77]:
```suggestion
                new InvalidOperationException("Unable to serialize 'test' to the scalar type 'Int'."));
```

File: src/GraphQL/Utilities/SchemaBuilder.cs [hunk 41]
```diff
@@ -498,11 +498,12 @@ private EnumValueDefinition ToEnumValue(GraphQLEnumValueDefinition valDef)
 
         protected virtual QueryArgument ToArgument(GraphQLInputValueDefinition inputDef)
         {
-            return new QueryArgument(ToGraphType(inputDef.Type))
+            var graphType = ToGraphType(inputDef.Type);
```
Comment (sungam3r) [inline src/GraphQL/Utilities/SchemaBuilder.cs:501]: Is something special here in moving this line from property initialization? I see another usage of `  ResolvedType = ToGraphType(inputDef.Type),` in ` protected virtual FieldType ToFieldType(string parentTypeName, GraphQLInputValueDefinition inputDef)`.

File: src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs [hunk 42]
```diff
@@ -111,9 +111,15 @@ public void ListOfNonNull_containing_null_should_bubble_up_the_null()
             var errors = new[]
             {
                 new ExecutionError("Error trying to resolve field 'listOfNonNullable'.", new InvalidOperationException(
-                    "Cannot return a null member within a non-null list for list index 1."))
+                    "Cannot return null for non-null type. Field: listOfNonNullable, Type: String!."))
```
Comment (sungam3r) [inline src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs:114]: for **a** non-null type ?

File: src/GraphQL/Utilities/SchemaBuilder.cs (hunk 41 above)
Comment (Shane32) [reply src/GraphQL/Utilities/SchemaBuilder.cs:501]: The old code called ToGraphType twice; I reduced it to one call.  However, we can put it back in the constructor and eliminate setting `ResolvedType` (since it's already set within the constructor), if you like.

I really don't know anything about this code; I just fixed the default value handling.

File: src/GraphQL/Utilities/SchemaBuilder.cs [hunk 43]
```diff
@@ -498,11 +498,12 @@ private EnumValueDefinition ToEnumValue(GraphQLEnumValueDefinition valDef)
...
+            return new QueryArgument(graphType)
```
Comment (Shane32) [inline src/GraphQL/Utilities/SchemaBuilder.cs:502]:
```suggestion
            return new QueryArgument(ToGraphType(inputDef.Type))
```

File: src/GraphQL/Utilities/SchemaBuilder.cs [hunk 44]
```diff
@@ -498,11 +498,12 @@ private EnumValueDefinition ToEnumValue(GraphQLEnumValueDefinition valDef)
...
             {
                 Name = (string)inputDef.Name.Value,
-                DefaultValue = inputDef.DefaultValue.ToValue(),
-                ResolvedType = ToGraphType(inputDef.Type),
+                DefaultValue = inputDef.DefaultValue,
+                ResolvedType = graphType,
```
Comment (Shane32) [inline src/GraphQL/Utilities/SchemaBuilder.cs:506]:
```suggestion
```

File: src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs (hunk 42 above)
Comment (Shane32) [reply src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs:114]: I agree.  (Personally I think this whole message could be revised.)

Comment (Shane32) [reply src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs]: Done

File: src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs [hunk 45]
```diff
@@ -111,9 +111,15 @@ public void ListOfNonNull_containing_null_should_bubble_up_the_null()
...
                 {
-                    Path = new object[] {"nonNullableDataGraph", "listOfNonNullable"}
+                    Path = new object[] {"nonNullableDataGraph", "listOfNonNullable", 1}
+                },
+
+                new ExecutionError("Error trying to resolve field 'listOfNonNullable'.", new InvalidOperationException(
```
Comment (sungam3r) [inline src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs:119]: I see that parent `nonNullableDataGraph` is non-null too. The error occurred on the **element** of the array but error message tals about array field itself (OK, `Path` is a hint for us that in fact the error occurred on the element). My question is why we do not see the same error message for the parent ``nonNullableDataGraph` field (and even maybe parent of parent and so on)? And the second question - do we need to add an error related to the array **element** (not array itself)? I get the impression that now there is no clear zone of responsibility about which node should add an error and what error.

Comment (Shane32) [reply src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs:119]: The spec prevents us from adding errors to parents due to nulls bubbling up:

> If the field returns null because of an error which has already been added to the "errors" list in the response, the "errors" list must not be further affected. That is, only one error should be added to the errors list per field.

Comment (Shane32) [reply src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs:119]: At least, I think that's what it says.  There's a bunch of paragraphs on it, and it seems to me that we should be listing 1+ errors, then bubbling up the null as far as necessary.  Which is what currently happens.

File: src/GraphQL/Utilities/SchemaBuilder.cs (hunk 41 above)
Comment (sungam3r) [reply src/GraphQL/Utilities/SchemaBuilder.cs:501]: 🤦 I see now, my bad. Just remove line with property initialization and return back `return new QueryArgument(ToGraphType(inputDef.Type))`.

File: src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs (hunk 45 above)
Comment (Shane32) [reply src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs:119]: > Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.

So it doesn't say anything about additional field errors being thrown.  It just says that when there's a field error due to non-nullability, it should bubble up as far as necessary.

Comment (Shane32) [reply src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs:119]: So it seems to me that we list the error as far down the rabbit-hole as possible (whatever first caused the error), then bubble up the null as much as necessary.  Which is how it works now.  If a resolver or serialization error occurs, the error is recorded, and then null is bubbled up without any additional errors listed.  Best I can read the spec, that's what is intended.  Keep in mind the caller knows the nullability graph, and the path of the error, and can deduce from the message why the parent nodes are null.

File: src/GraphQL/Utilities/SchemaBuilder.cs (hunk 41 above)
Comment (Shane32) [reply src/GraphQL/Utilities/SchemaBuilder.cs:501]: See two code suggestions below; merge them both if you like and it should compile and test properly.

**Comment by Shane32** [comment]
I have to go to bed; it's 4am for me!

File: src/GraphQL/Types/Scalars/SByteGraphType.cs [hunk 46]
```diff
@@ -12,25 +12,56 @@ public class SByteGraphType : ScalarGraphType
...
+            null => null,
+            int i => checked((sbyte)i),
+            byte b => checked((sbyte)b),
+            short s => checked((sbyte)s),
+            ushort us => checked((sbyte)us),
+            uint ui => checked((sbyte)ui),
+            long l => checked((sbyte)l),
+            ulong ul => checked((sbyte)ul),
+            BigInteger bi => (sbyte)bi,
+            float f => checked((sbyte)f),
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: Unfortunately such work with floating point numbers results in loss of accuracy. See `SByteGraphTypeTests.Coerces_given_inputs_to_overflow_exception`, case `999.99`. Add `1.3` case. It fails since `checked((sbyte)1.3)` yields `1`. That is why when you asked whether it was necessary to add new cases for all the numeric scalars for parsing, then I said yes but maybe exclude floating-point ones exactly because truncation problem. The same problem was in past with `DateGraphType` that "normally" worked with time component simply truncating it. Now it throw exception `Expected date to have no time component` to prevent loss of accuracy. 

You may add something like
```csharp
        private static sbyte Ret(float f) => checked((sbyte)f == f ? (sbyte)f : throw new InvalidOperationException("Loss of accuracy for scalar 'XXX' parsing 'value'."));
```

File: src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs (hunk 45 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Bugs/BubbleUpTheNullToNextNullable.cs:119]: Maybe, maybe...

> That is, only one error should be added to the errors list **per field**.


Per field. This allows you to ambiguously interpret the specification. @benjie Could you help us with understanding spec, please?

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 47]
```diff
@@ -58,13 +65,16 @@ public abstract class ScalarGraphType : GraphType
         /// server-side representation.
         /// <br/><br/>
         /// This method can be overridden to validate input values without directly getting those values, i.e. without boxing.
+        /// <br/><br/>
+        /// This method must return <see langword="true"/> when passed a <see cref="NullValue"/> node.
         /// </summary>
-        /// <param name="value">AST value node. Must not be <see langword="null"/>.</param>
+        /// <param name="value">AST value node. Must not be <see langword="null"/> or <see cref="NullValue"/>.</param>
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:71]:
```suggestion
        /// <param name="value">AST value node. Must not be <see langword="null"/>, but may be <see cref="NullValue"/>.</param>
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 48]
```diff
@@ -99,7 +112,7 @@ public virtual bool CanParseValue(object value)
         /// Checks that the provided value is a valid default value.
         /// This method should not throw an exception.
         /// </summary>
-        /// <param name="value">The value to examine. Must not be <see langword="null"/>.</param>
+        /// <param name="value">The value to examine. Must not be <see langword="null"/>, as that indicates the lack of a default value.</param>
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:115]: > as that indicates the lack of a default value

But now `IsValidDefault(null)` yields `true` since by default `ToAST(null)` yields `new NullValue()`.

Add `if (value == null) return false` ?

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 49]
```diff
@@ -116,41 +129,50 @@ public virtual bool IsValidDefault(object value)
...
+        }
+
+        // this is often called for serialization errors, since Serialize calls ParseValue by default
+        // also may be called for serialization errors during ToAST, since ToAST calls Serialize by default, which by default calls ParseValue
+        internal object ThrowValueConversionError(object value)
+        {
+            throw new InvalidOperationException($"Unable to convert '{value}' to the scalar type '{Name}'");
+        }
+
+        // also may be called for serialization errors during ToAST, since ToAST calls Serialize by default
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:172]:
```suggestion
        // also may be called by ScalarGraphType descendants for serialization errors during ToAST, since ToAST calls Serialize by default
```

Since "base" `Serialize` calls `ParseValue` which should not call `ThrowSerializationError`.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 50]
```diff
@@ -116,41 +129,50 @@ public virtual bool IsValidDefault(object value)
...
+        internal object ThrowSerializationError(object value)
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:173]: Why `internal`? Maybe `protected` instead of `internal` for each `ThrowXXX` methods?

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 51]
```diff
@@ -116,41 +129,50 @@ public virtual bool IsValidDefault(object value)
...
+                uint ui => new LongValue(ui),
+                long l => new LongValue(l),
+                ulong ul => new BigIntValue(ul),
+                BigInteger bi => new BigIntValue(bi),
+                decimal d => new DecimalValue(d),
+                float f => new FloatValue(f),
+                double d => new FloatValue(d),
+                string s => new StringValue(s),
+                null => new NullValue(),
+                _ => throw new System.NotImplementedException($"Please override the '{nameof(ToAST)}' method of the '{GetType().Name}' scalar to support this operation.")
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:156]:
```suggestion
                _ => throw new NotImplementedException($"Please override the '{nameof(ToAST)}' method of the '{GetType().Name}' scalar to support this operation.")
```

File: src/GraphQL/Types/Scalars/ShortGraphType.cs [hunk 52]
```diff
@@ -12,25 +12,56 @@ public class ShortGraphType : ScalarGraphType
...
+            null => null,
+            int i => checked((short)i),
+            sbyte sb => checked((short)sb),
+            byte b => checked((short)b),
+            ushort us => checked((short)us),
+            uint ui => checked((short)ui),
+            long l => checked((short)l),
+            ulong ul => checked((short)ul),
+            BigInteger bi => (short)bi,
+            float f => checked((short)f),
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ShortGraphType.cs:45]: Loss of accuracy for 
 float f => checked((short)f),
double d => checked((short)d),
decimal d => checked((short)d),

File: src/GraphQL/Types/Scalars/ShortGraphType.cs [hunk 53]
```diff
@@ -12,25 +12,56 @@ public class ShortGraphType : ScalarGraphType
...
+            short _ => value,
+            null => null,
+            int i => checked((short)i),
+            sbyte sb => checked((short)sb),
+            byte b => checked((short)b),
+            ushort us => checked((short)us),
+            uint ui => checked((short)ui),
+            long l => checked((short)l),
+            ulong ul => checked((short)ul),
+            BigInteger bi => (short)bi,
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ShortGraphType.cs:44]: Why without `checked`? Other widening conversions like ` byte b => checked((short)b),` have `checked`.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs [hunk 54]
```diff
@@ -12,25 +12,56 @@ public class ShortGraphType : ScalarGraphType
...
+            float f => checked((short)f),
+            double d => checked((short)d),
+            decimal d => checked((short)d),
+            _ => ThrowValueConversionError(value)
+        };
+
+        /// <inheritdoc/>
+        public override object Serialize(object value) => value switch
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: Why copy-paste this from `ParseValue` that is called by default from `ScalarGraphType.Serialize` ? Also `ParseValue` has cases for floating point numbers.

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: I wouldn't.  We support floating-point values because of how the serializers work.  They are only supported in ParseValue, not ParseLiteral.  And by definition, `(sbyte)f == f` may return false because 3.0 is not stored as exactly 3.  And I don't think we should be writing `Math.Abs(f - (float)(sbyte)f) < float.Epsilon` which is the proper way to perform this check. If we want to "fix" the problem, we should build merge the deserialization engine with GraphQL, so that it can read the json data in the correct format the first time, rather than having a bunch of TryGet code (see ObjectDictionaryConverter) and then have to coerce the value.

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: > See SByteGraphTypeTests.Coerces_given_inputs_to_overflow_exception, case 999.99. Add 1.3 case. It fails since checked((sbyte)1.3) yields 1

I am interested in what to do now in the case of 1.3 for `sbyte`.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 48 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:115]: Sure.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 55]
```diff
@@ -99,7 +112,7 @@ public virtual bool CanParseValue(object value)
         /// Checks that the provided value is a valid default value.
         /// This method should not throw an exception.
         /// </summary>
-        /// <param name="value">The value to examine. Must not be <see langword="null"/>.</param>
+        /// <param name="value">The value to examine. Must not be <see langword="null"/>, as that indicates the lack of a default value.</param>
         public virtual bool IsValidDefault(object value)
         {
             try
```
Comment (Shane32) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:118]:
```suggestion
            if (value == null) return false;
            
            try
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 50 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs:175]: Sure.

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: I do not urge to use math. You can generally abandon the support of the convertion from floating point numbers. I'm talking about that now the code works incorrectly for the case described above.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 52 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:45]: Correct.  Not making changes here.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 53 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:44]: Sure, I'll add it in.  FYI, it's not a native conversion, so checked/unchecked does not have any effect (tested & confirmed).  It simply calls the BigInteger explicit cast operator.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:44]: We also have tests that confirm all these casts throw exceptions properly, for every type, to every type.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 54 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: Because within the resolver, you should be returning values of the correct type.  The only reason floating-point support was added for ParseValue is because of the fact that json deserializers may not deserialize values to the correct native .NET type.

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: > I am interested in what to do now in the case of 1.3 for `sbyte`.

We can introduce proper math, as described above, to check for this scenario.  We cannot add `(sbyte)f == f`.  I would not do this.  Or we can ignore the error, just as it was done before.

Note that this is only for ParseValue, and only there because of the nature of json deserializers.  This is not a bug that needs to be fixed.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 53 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:44]: Good. I thought so. Just the reader will arise less questions if everywhere will be equally.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 54 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: > Because within the resolver, you should be returning values of the **correct** type. 

What do you mean ? Is it correct to return `(int)1` from resolver for `Short` ? Resolver returns internal representation of the scalar. Then this value converted to the external representation.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: I meant that you should be returning an integer type for integers.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: We can be more explicit in our support for internally-represented values, only accepting `int` for `IntGraphType`, and `sbyte` for `SByteGraphType`.  At this point, the added flexibility is fully overflow-checked and does not result in loss of precision.  So I see it as a "bonus feature".

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: >  Adding the check you suggested will lead to bugs for certain values on certain platforms.

It was just an example.

> If you like, perhaps we can remove the floating point conversions for the types that are int or smaller, hoping and assuming that the json deserializer uses an int data type rather than double during its deserialization process.

I'm OK with remove floating point conversions from both `ParseValue` and `Serialize`. It seems to me that integers and floating point numbers do not need to mix. We already have `IntValue` and `FloatValue` different literals for this reason.

> and only there because of the nature of json deserializers. This is not a bug that needs to be fixed.

I don't understand and disagree.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 54 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: "Bonus feature" is good but let's separate integers from floating point numbers. This is a line crossing which we take risks. Remember about `DateGraphType` and time component. Let's be consistent.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: Then, most likely, we can remove floating-point conversions from `int` and smaller.  `uint`, `long`, and `ulong` probably need floating-point conversions for newtonsoft's json converter to work properly.  Would you agree?

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: I'll just write some tests to demonstrate the problem.  If the problem doesn't exist, then we don't need to worry about it.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 54 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: > uint, long, and ulong probably need floating-point conversions for newtonsoft's json converter to work properly

Why? Let's test it.

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs:52]: Are you talking about that rather big number from JSON string will be deserialized by Newtonsoft/System.Text.Json not as `int/long/ulong/BigInt`, but always as `double` so we de facto always need conversion from `double` to integer scalars ?

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: 👍

File: src/GraphQL/Types/Scalars/GuidGraphType.cs [hunk 56]
```diff
@@ -9,23 +9,45 @@ namespace GraphQL.Types
...
+            Guid _ => true,
+            string s => Guid.TryParse(s, out _),
+            null => true,
+            _ => false
+        };
+
+        /// <inheritdoc/>
+        public override object Serialize(object value) => value switch
+        {
+            Guid g => g.ToString(),
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/GuidGraphType.cs:48]:
```suggestion
            Guid g => g.ToString("D", CultureInfo.InvariantCulture),
```
Let's be more explicit.

File: src/GraphQL/Types/Scalars/IdGraphType.cs [hunk 57]
```diff
@@ -23,31 +23,39 @@ public IdGraphType()
...
+            int _ => value,
+            long _ => value,
+            _ => value?.ToString()
+        };
+
+        /// <inheritdoc/>
+        public override bool CanParseValue(object value) => true;
+
+        /// <inheritdoc/>
+        public override object Serialize(object value) => value?.ToString();
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/IdGraphType.cs:59]:
```suggestion
        public override object Serialize(object value) => ParseValue(value)?.ToString();
```

File: src/GraphQL/Types/Scalars/IdGraphType.cs [hunk 58]
```diff
@@ -23,31 +23,39 @@ public IdGraphType()
...
             _ => false
         };
 
         /// <inheritdoc/>
-        public override IValue ToAST(object value) => new StringValue(value.ToString());
+        public override object ParseValue(object value) => value switch
+        {
+            int _ => value,
+            long _ => value,
+            _ => value?.ToString()
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/IdGraphType.cs:52]: I suggest to add many cases for integer numbers and call `ThrowValueConversionError` for default case. I would not convert any object (`DateTime`, `Guid`, `bool`, etc.) into string representation how now it does.

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/IdGraphType.cs:52]: Of cource `CanParseValue` should be changed too.

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: I was unable to reproduce the problem.  Looks like the json converters do not convert to floating point for integer numbers.  I'll remove the floating-point support from ParseValue.  I added tests for both json converters to confirm this.

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: Add test for
```json
{
  "someBigNumber": 1646176147698146586816969619696946176496969696996969869
}
```

After all, the deserialization of variables occurs in `Dictionary<string, object>`, right?

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 59]
```diff
@@ -18,13 +19,15 @@ public abstract class ScalarGraphType : GraphType
...
         /// for generating an object which can eventually be serialized by some transport-focused API.
+        /// <br/><br/>
+        /// This method must handle a value of <see langword="null"/>.
         /// </summary>
-        /// <param name="value">Resolved value. Must not be <see langword="null"/>.</param>
+        /// <param name="value">Resolved value. May be <see langword="null"/>.</param>
         /// <returns>
         /// The returned value of a the result coercion is part of the overall execution result.
         /// Normally this value is a primitive value like String or Integer to make it easy for
         /// the serialization layer. For complex types like a Date or Money Scalar this involves
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:29]:
```suggestion
        /// the serialization layer. For complex types like a Date or Money scalar this involves
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 29 above)
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:30]:
```suggestion
        /// formatting the value. Returning <see langword="null"/> is valid.
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 60]
```diff
@@ -18,13 +19,15 @@ public abstract class ScalarGraphType : GraphType
         /// Since GraphQL specifies no response format, Serialize is not
         /// responsible for preparing the scalar for transport to the client. It is only responsible
         /// for generating an object which can eventually be serialized by some transport-focused API.
+        /// <br/><br/>
+        /// This method must handle a value of <see langword="null"/>.
         /// </summary>
-        /// <param name="value">Resolved value. Must not be <see langword="null"/>.</param>
+        /// <param name="value">Resolved value. May be <see langword="null"/>.</param>
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:25]:
```suggestion
        /// <param name="value">Resolved value (internal scalar representation). May be <see langword="null"/>.</param>
```

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: Tests proved that the `ObjectDictionaryConverter` needed to be changed to give priority to `BigInteger` over `double` and `decimal` or else a large value that can be contained "without loss of precision" as a floating-point value would not be stored as a `BigInteger`, breaking deserialization.  I've made the change.  No issue with newtonsoft.

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: Hmm, I did not think about it when I added `BigInteger` support. That is, the change should lead to the fact that we will become in more cases to deserialize the number into `BigInteger` instead of `double`?

> No issue with newtonsoft.

Why?

File: src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs [hunk 61]
```diff
@@ -41,10 +34,18 @@ public TimeSpanMillisecondsGraphType()
             TimeSpan _ => value, // no boxing
             int i => TimeSpan.FromMilliseconds(i),
             long l => TimeSpan.FromMilliseconds(l),
-            _ => null
+            null => null,
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:37]: Add other integer cases ?

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs:45]: And we don't even have proper serialization support for BigInteger values.  I'm fixing that also.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 52 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs]: Floating-point parsing removed.

File: src/GraphQL/Types/Scalars/ShortGraphType.cs (hunk 54 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/ShortGraphType.cs]: Removed duplicate code as requested.

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs]: Removed floating-point parsing as requested.  Fixed BigInteger parsing and serialization (both broken).

File: src/GraphQL/Types/Scalars/IdGraphType.cs (hunk 57 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/IdGraphType.cs:59]: Serialize should handle Guids.  They are commonly used for identifiers.  Normally I would say that ParseValue should not interpret them, as external representations should be strings (ideally), or numbers.  I can put it in there anyway - ?

File: src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs (hunk 61 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:37]: Ok

Comment (Shane32) [reply src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:38]: Done.  Note that `FromMilliseconds` and `FromSeconds` accept a `double`.  We could also support floating-point values here.  I did not do so yet.

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs]: > Hmm, I did not think about it when I added `BigInteger` support. That is, the change should lead to the fact that we will become in more cases to deserialize the number into `BigInteger` instead of `double`?
> 
> > No issue with newtonsoft.
> 
> Why?

Newtonsoft has built-in support for BigInteger that takes precedence over floating-point types.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs]: > Hmm, I did not think about it when I added `BigInteger` support. That is, the change should lead to the fact that we will become in more cases to deserialize the number into `BigInteger` instead of `double`?

Yes but the scalar will convert it to the proper type.  It will never be presented as a BigInteger, even if they access `Variables` directly, as they will be accessing the copy of the variables after it has been deserialized by the scalars via `ParseValue`.  It also should not be any slower, because already the code attempts to read it both as a `BigInteger` and a `double`.

File: src/GraphQL/Types/Scalars/IdGraphType.cs (hunk 57 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/IdGraphType.cs]: > Serialize should handle Guids.

OK but not bools anyway.

> Normally I would say that ParseValue should not interpret them

🤔 OK. So `ParseValue` and `Serialize` will be different a little.

File: src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs (hunk 61 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:38]: Yes, **internal** representations of these scalars accept but not external format. Let's keep it as integer values.

File: src/GraphQL/Types/Scalars/IdGraphType.cs (hunk 58 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/IdGraphType.cs]: Good

File: src/GraphQL/Types/Scalars/IdGraphType.cs (hunk 57 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/IdGraphType.cs]: I didn't separate/duplicate the code, so as it is now, since Serialize calls ParseValue, ParseValue can handle a Guid.... lmk if you think it should be changed.

File: src/GraphQL/Types/Scalars/SByteGraphType.cs (hunk 46 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/SByteGraphType.cs]: > Yes but the scalar will convert it to the proper type.

I understand.

File: src/GraphQL/Types/Scalars/IdGraphType.cs (hunk 57 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/IdGraphType.cs]: OK. I will review again.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs [hunk 62]
```diff
@@ -99,9 +112,11 @@ public virtual bool CanParseValue(object value)
         /// Checks that the provided value is a valid default value.
         /// This method should not throw an exception.
         /// </summary>
-        /// <param name="value">The value to examine. Must not be <see langword="null"/>.</param>
+        /// <param name="value">The value to examine. Must not be <see langword="null"/>, as that indicates the lack of a default value.</param>
         public virtual bool IsValidDefault(object value)
         {
+            if (value == null) return false;
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/ScalarGraphType.cs:118]:
```suggestion
            if (value == null)
                return false;
```

File: src/GraphQL.Tests/Execution/UnionInterfaceTests.cs [hunk 63]
```diff
@@ -138,11 +138,13 @@ public void executes_using_union_types()
...
                   ""__typename"": ""Person"",
                   ""name"": ""John"",
-                  ""pets"": null
+                  ""pets"": [ null, null ]
                 }
             ";
 
-            var result = AssertQueryWithErrors(query, expected, root: _john, rules: Enumerable.Empty<IValidationRule>(), expectedErrorCount: 1);
+            var result = AssertQueryWithErrors(query, expected, root: _john, rules: Enumerable.Empty<IValidationRule>(), expectedErrorCount: 2);
+            result.Errors[0].Message.ShouldBe("Error trying to resolve field 'pets'.");
```
Comment (sungam3r) [inline src/GraphQL.Tests/Execution/UnionInterfaceTests.cs:146]: изображение

1?

File: src/GraphQL.Tests/Types/IdGraphTypeTests.cs [hunk 64]
```diff
@@ -11,9 +10,9 @@ public class IdGraphTypeTests
         private readonly IdGraphType _type = new IdGraphType();
 
         [Fact]
-        public void parse_value_null_throws()
+        public void parse_value_null_returns_null()
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/IdGraphTypeTests.cs:13]: Any tests for accepting Guid, Long, etc. for ID scalar ?

File: src/GraphQL.Tests/Execution/AstFromValueTests.cs [hunk 65]
```diff
@@ -8,11 +8,17 @@ namespace GraphQL.Tests.Execution
 {
     public class AstFromValueTests
     {
+        [Fact]
+        public void throws_for_null_graphtype()
+        {
+            Should.Throw<ArgumentNullException>(() => ((IGraphType)null).ToAST(null));
```
Comment (sungam3r) [inline src/GraphQL.Tests/Execution/AstFromValueTests.cs:14]:
```suggestion
            Should.Throw<ArgumentNullException>(() => ((IGraphType)null).ToAST(true));
```
I think it's better to pass non-null argument so it's clear that exception belongs to `this` argument.

File: src/GraphQL/Types/Scalars/BooleanGraphType.cs [hunk 66]
```diff
@@ -9,15 +9,33 @@ namespace GraphQL.Types
...
         /// <inheritdoc/>
-        public override IValue ToAST(object value) => new BooleanValue((bool)value);
+        public override bool CanParseValue(object value) => value is bool || value == null;
+
+        /// <inheritdoc/>
+        public override IValue ToAST(object value) => value switch
+        {
+            bool b => new BooleanValue(b),
+            null => new NullValue(),
+            _ => null
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/BooleanGraphType.cs:38]: ? `ScalarGraphType` throws on unknown value.

File: src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs [hunk 67]
```diff
@@ -18,21 +19,14 @@ public TimeSpanMillisecondsGraphType()
...
-            int i => (long)i,
-            long _ => value,
-            _ => null
-        };
-
         /// <inheritdoc/>
         public override object ParseLiteral(IValue value) => value switch
         {
             IntValue intValue => TimeSpan.FromMilliseconds(intValue.Value),
             LongValue longValue => TimeSpan.FromMilliseconds(longValue.Value),
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:26]: By the way `TimeSpan.FromMilliseconds(long.MaxValue)` will throw:
```
System.OverflowException: 'TimeSpan overflowed because the duration is too long.'
```

The same for `FromSeconds`.

File: src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs [hunk 68]
```diff
@@ -18,21 +19,14 @@ public TimeSpanMillisecondsGraphType()
                 "The `Milliseconds` scalar type represents a period of time represented as the total number of milliseconds.";
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:19]:
```suggestion
                "The `Milliseconds` scalar type represents a period of time represented as the total number of milliseconds in range [-922337203685477, 922337203685477].";
```

What do you think if we prohibit negative values for `Milliseconds` and `Seconds`? Now both accept negative values.

> represents a period of time

What is period of time?

`TimeSpan.FromMilliseconds(-100)` works fine and yields `{-00:00:00.1000000}`. Do we need to continue to take negative values?

File: src/GraphQL/Types/Scalars/TimeSpanSecondsGraphType.cs [hunk 69]
```diff
@@ -19,21 +20,14 @@ public TimeSpanSecondsGraphType()
                 "The `Seconds` scalar type represents a period of time represented as the total number of seconds.";
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/TimeSpanSecondsGraphType.cs:20]:
```suggestion
                "The `Seconds` scalar type represents a period of time represented as the total number of seconds in range [-922337203685, 922337203685].";
```

File: src/GraphQL/Types/Scalars/UriGraphType.cs [hunk 70]
```diff
@@ -10,13 +10,29 @@ namespace GraphQL.Types
...
 
         /// <inheritdoc/>
-        public override IValue ToAST(object value) => new StringValue(ParseValue(value).ToString());
+        public override object Serialize(object value) => value switch
+        {
+            string s => new Uri(s).ToString(), //validate uri
+            Uri u => u.ToString(),
+            null => null,
+            _ => ThrowSerializationError(value)
+        };
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/UriGraphType.cs:36]:
```suggestion
        public override object Serialize(object value) => ParseValue(value)?.ToString();
```

The same as for `IdGraphType`.

File: src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs (hunk 68 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:19]: I don’t see a reason to prohibit negative numbers. We don’t know how the field will be used. Perhaps it’s a time offset from DOMContentLoaded, and a negative value is used to log the negative time offset indicating when the JavaScript started executing. Could be anything. (Which is why also I would suggest we change the type to double instead of long)

Comment (Shane32) [reply src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:19]: (All JavaScript numbers are doubles anyway )

File: src/GraphQL/Types/Scalars/UriGraphType.cs (hunk 70 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/UriGraphType.cs:36]: This cannot be done here.  ParseValue converts strings to Uris.  Serialize converts Uris to strings.

File: src/GraphQL.SystemTextJson/JsonConverterBigInteger.cs [hunk 71]
```diff
@@ -33,18 +34,19 @@ public static bool TryGetBigInteger(ref Utf8JsonReader reader, out BigInteger bi
...
+            }
 
-            // example:
-            // BigInteger 636474637870330463636474637870330463636474637870330463 -> double 6.3647463787033043E+53
-
-            // see Very_Very_Long_Number_Should_Return_As_Is_For_BigInteger and Very__Very_Long_Number_In_Input_Should_Work_For_BigInteger tests
-            // tests succeed because the original (expected) string result first parsed to ExecutionResult and then converted back to string,
-            // so finally we compare 6.3647463787033043E+53 with 6.3647463787033043E+53, not with original number value 636474637870330463636474637870330463636474637870330463
-            writer.WriteNumberValue((double)value);
+            var s = value.ToString(NumberFormatInfo.InvariantInfo);
```
Comment (sungam3r) [inline src/GraphQL.SystemTextJson/JsonConverterBigInteger.cs:47]: Please add link to https://stackoverflow.com/questions/64788895/serialising-biginteger-using-system-text-json in comments for this block of code.

File: src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs (hunk 68 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:19]: OK. So I suggest to add only range in description.

File: src/GraphQL/Types/Scalars/UriGraphType.cs (hunk 70 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/UriGraphType.cs:36]: Yes, the new code does it, nothing changes.

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/UriGraphType.cs:36]: Serialize: string or uri -> uri -> string

File: src/GraphQL/Types/Scalars/BooleanGraphType.cs (hunk 66 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/BooleanGraphType.cs:38]: > Returning null indicates a failed conversion

Which is actually broken; I fixed that.

In any case, I added another protected method for this exception.

File: src/GraphQL.SystemTextJson/JsonConverterBigInteger.cs (hunk 71 above)
Comment (Shane32) [reply src/GraphQL.SystemTextJson/JsonConverterBigInteger.cs:48]: Done

File: src/GraphQL.Tests/Execution/UnionInterfaceTests.cs (hunk 63 above)
Comment (Shane32) [reply src/GraphQL.Tests/Execution/UnionInterfaceTests.cs:146]: Yes, fixed.

Comment (Shane32) [reply src/GraphQL.Tests/Execution/UnionInterfaceTests.cs:146]: (whoops!)

File: src/GraphQL/Types/Scalars/UriGraphType.cs (hunk 70 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/UriGraphType.cs]: True.

Done.

**Comment by Shane32** [comment]
I tried, but it won't work - it would have to be static.  Or we make more internal methods

**Comment by sungam3r** [comment]
I'm done for today, 40/63 files reviewed.

**Comment by Shane32** [comment]
And if it's static it won't have a reference to Name

File: src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs (hunk 67 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/TimeSpanMillisecondsGraphType.cs:26]: 👍

File: src/GraphQL.Tests/Types/IdGraphTypeTests.cs (hunk 64 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/IdGraphTypeTests.cs:20]: Added a bunch of tests.

**Comment by Shane32** [comment]
> There wasn't any, but there should have been for `EnumerationGraphType`. Added.

Added a test for this also.

**Comment by Shane32** [comment]
Added toAST tests for all numeric types.  Added some more TimeSpan tests.

File: src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs [hunk 72]
```diff
@@ -86,29 +85,16 @@ private static object ReadNumber(ref Utf8JsonReader reader)
                 return i;
             else if (reader.TryGetInt64(out long l))
                 return l;
+            else if (JsonConverterBigInteger.TryGetBigInteger(ref reader, out var bi))
+            {
+                return bi;
+            }
```
Comment (sungam3r) [inline src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs:91]:
```suggestion
                return bi;
```

File: src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs [hunk 73]
```diff
@@ -86,29 +85,14 @@ private static object ReadNumber(ref Utf8JsonReader reader)
                 return i;
             else if (reader.TryGetInt64(out long l))
                 return l;
+            else if (JsonConverterBigInteger.TryGetBigInteger(ref reader, out var bi))
+                return bi;
             else if (reader.TryGetDouble(out double d))
             {
```
Comment (sungam3r) [inline src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs:91]:
```suggestion
```

File: src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs [hunk 74]
```diff
@@ -86,29 +85,14 @@ private static object ReadNumber(ref Utf8JsonReader reader)
...
-                // value from json       : 636474637870330463636474637870330463636474637870330463
-                // successfully parsed d : 6.3647463787033043E+53
-                // new BigInteger(d)     : 636474637870330432588044308848152942336795574685138944
-                if (JsonConverterBigInteger.TryGetBigInteger(ref reader, out var bi))
-                {
-                    if (bi != new BigInteger(d))
-                        return bi;
-                }
                 return d;
             }
```
Comment (sungam3r) [inline src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs:93]:
```suggestion
```

File: src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs [hunk 75]
```diff
@@ -86,29 +85,14 @@ private static object ReadNumber(ref Utf8JsonReader reader)
...
             else if (reader.TryGetDecimal(out decimal dm))
             {
```
Comment (sungam3r) [inline src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs:95]:
```suggestion
```

File: src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs [hunk 76]
```diff
@@ -86,29 +85,14 @@ private static object ReadNumber(ref Utf8JsonReader reader)
...
-                // the same idea as for a double value above
-                if (JsonConverterBigInteger.TryGetBigInteger(ref reader, out var bi))
-                {
-                    if (bi != new BigInteger(dm))
-                        return bi;
-                }
                 return dm;
             }
```
Comment (sungam3r) [inline src/GraphQL.SystemTextJson/ObjectDictionaryConverter.cs:97]:
```suggestion
```

File: src/GraphQL.Tests/Bugs/Bug1773.cs [hunk 77]
```diff
@@ -51,40 +51,45 @@ public void nonnull_list_valid()
         [Fact]
         public void nonnull_list_throws_when_null()
         {
-            AssertQueryWithError("{testListNullInvalid}", "{\"testListNullInvalid\": null}", "Error trying to resolve field 'testListNullInvalid'.", 1, 2, new[] { "testListNullInvalid" },
-                new InvalidOperationException("Cannot return a null member within a non-null list for list index 0."));
+            AssertQueryWithError("{testListNullInvalid}", "{\"testListNullInvalid\": null}", "Error trying to resolve field 'testListNullInvalid'.", 1, 2, new object[] { "testListNullInvalid", 0 },
+                new InvalidOperationException("Cannot return null for a non-null type. Field: testListNullInvalid, Type: Int!."));
```
Comment (sungam3r) [inline src/GraphQL.Tests/Bugs/Bug1773.cs:55]: This message is confusing a bit, `testListNullInvalid` has `[Int!]` type, not `Int!`. See https://github.com/graphql-dotnet/graphql-dotnet/pull/2341/files#r587278824

File: src/GraphQL.Tests/Bugs/Bug1773.cs [hunk 78]
```diff
@@ -51,40 +51,45 @@ public void nonnull_list_valid()
...
         }
 
         [Fact]
         public void list_throws_for_invalid_type()
         {
-            // TODO: does not yet fully meet spec (does not return members of lists that are able to be serialized, with nulls and individual errors for unserializable values)
-            AssertQueryWithError("{testListInvalidType}", "{\"testListInvalidType\": null}", "Error trying to resolve field 'testListInvalidType'.", 1, 2, new[] { "testListInvalidType" },
-                new FormatException("Input string was not in a correct format."), localizedMessage: "Входная строка имела неверный формат.");
+            AssertQueryWithError("{testListInvalidType}", "{\"testListInvalidType\": [ null ]}", "Error trying to resolve field 'testListInvalidType'.", 1, 2, new object[] { "testListInvalidType", 0 },
```
Comment (sungam3r) [inline src/GraphQL.Tests/Bugs/Bug1773.cs:61]: The same "problem" here as https://github.com/graphql-dotnet/graphql-dotnet/pull/2341/files#r588111945 .
`testListInvalidType` is nullable array of nullable enums. `Error trying to resolve field 'testListInvalidType'` seems confusing a little since `testListInvalidType` field was successfully returned. I understand that in the case of arrays, we do not have an array element name. There is only an index. We now see this index in `Path`. It's good. But it is bad that an error message can be perceived completely differently.

I would prefer to see an error message like
`Error trying to resolve array element for field 'testListInvalidType'.` (**array element for** added)

File: src/GraphQL.Tests/Types/IdGraphTypeTests.cs [hunk 79]
```diff
@@ -11,41 +11,108 @@ public class IdGraphTypeTests
...
         {
-            _type.ParseValue("\"12345\"").ShouldBe("12345");
+            _type.Serialize(null).ShouldBeNull();
+        }
+
+        [Theory]
+        [InlineData(1)]
+        [InlineData(2L)]
+        [InlineData("hello")]
+        public void parse_literal_int_value_to_identifier(object value)
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/IdGraphTypeTests.cs:35]:
```suggestion
        public void parse_literal_value_to_identifier(object value)
```

File: src/GraphQL.Tests/Types/IdGraphTypeTests.cs [hunk 80]
```diff
@@ -11,41 +11,108 @@ public class IdGraphTypeTests
...
         [Fact]
-        public void parse_literal_long_value_to_identifier()
+        public void serialize_guid()
         {
-            long val = 12345;
-            _type.ParseLiteral(new LongValue(12345)).ShouldBe(val);
+            var g = new Guid("12345678901234567890123456789012");
+            var ret = _type.Serialize(g);
+            ret.ShouldBeOfType(typeof(string));
+            ret.ShouldBe(g.ToString());
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/IdGraphTypeTests.cs:115]:
```suggestion
            ret.ShouldBe(g.ToString("D", CultureInfo.InvariantCulture));
```

Explicit check.

File: src/GraphQL.Tests/Types/TimeSpanMillisecondsGraphTypeTests.cs [hunk 81]
```diff
@@ -65,13 +62,55 @@ public void coerces_TimeSpan_to_timespan()
...
+        [Theory]
+        [InlineData((byte)1)]
+        [InlineData((sbyte)2)]
+        [InlineData((short)3)]
+        [InlineData((ushort)4)]
+        [InlineData((int)5)]
+        [InlineData((uint)6)]
+        [InlineData((long)7)]
+        [InlineData((ulong)8)]
+        public void parsevalue_to_timespan(object value)
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/TimeSpanMillisecondsGraphTypeTests.cs:95]: I don's see any negative tests for `ParseValue` and `ParseLiteral` for `TimeSpanMillisecondsGraphType` and `TimeSpanSecondsGraphType`. Either add them or let's add all lost test cases in separate PR with the help of codecov coverage colored map.

File: src/GraphQL/GraphQLExtensions.cs [hunk 82]
```diff
@@ -566,15 +566,25 @@ public static bool IsValidDefault(this IGraphType type, object value)
...
+            if (type == null)
+                throw new ArgumentNullException(nameof(type));
+
             if (type is NonNullGraphType nonnull)
             {
-                if (value == null)
+                var astValue = ToAST(nonnull.ResolvedType, value);
+
+                if (astValue is NullValue)
                     throw new InvalidOperationException($"Unable to get an AST representation of type '{nonnull}' for null value.");
```
Comment (sungam3r) [inline src/GraphQL/GraphQLExtensions.cs:577]:
```suggestion
                    throw new InvalidOperationException($"Unable to get an AST representation of null value for type '{nonnull}'.");
```

I'm not sure how to say correctly. It seems to me that AST relates more to value than type.

File: src/GraphQL/Types/Scalars/DateGraphType.cs [hunk 83]
```diff
@@ -19,47 +19,52 @@ public DateGraphType()
...
 
         /// <inheritdoc/>
-        public override object ParseLiteral(IValue value)
-            => value is StringValue stringValue ? ParseValue(stringValue.Value) : null;
+        public override object ParseValue(object value) => value switch
+        {
+            DateTime d => ValidateDate(d, value), // no boxing
+            string stringValue => ParseDate(stringValue),
+            null => null,
+            _ => throw new FormatException($"Could not parse date. Expected either a string or a DateTime without time component. Value: {value}")
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/DateGraphType.cs:35]: Is this the only scalar that generates `FormatException` now?

File: src/GraphQL/Types/Scalars/IdGraphType.cs [hunk 84]
```diff
@@ -23,31 +24,47 @@ public IdGraphType()
             //    "as `\"4\"`) or integer (such as `4`) input value will be accepted as an `ID`.";
         }
 
-        /// <inheritdoc/>
-        public override object Serialize(object value) => value.ToString();
-
         /// <inheritdoc/>
         public override object ParseLiteral(IValue value) => value switch
         {
             StringValue str => ParseValue(str.Value),
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/IdGraphType.cs:30]:
```suggestion
            StringValue str => str.Value,
```

**Comment by sungam3r** [comment]
> I tried, but it won't work - it would have to be static. Or we make more internal methods

Only one method changes from `protected` to `protected internal`. Not?

File: src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs [hunk 85]
```diff
@@ -233,6 +238,28 @@ public override void VisitDirectiveArgumentDefinition(QueryArgument argument, Di
...
+
+            // validate default
+            if (argument.DefaultValue is GraphQLValue value)
+            {
+                argument.DefaultValue = Execution.ExecutionHelper.CoerceValue(argument.ResolvedType, Language.CoreToVanillaConverter.Value(value)).Value;
+            }
+            else if (argument.DefaultValue != null && !argument.ResolvedType.IsValidDefault(argument.DefaultValue))
+            {
+                throw new InvalidOperationException($"The default value of argument '{argument.Name}' of directive '{type.Name}' is invalid.");
+            }
```
Comment (sungam3r) [inline src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:250]: Can be merged into `ValidateQueryArgumentDefaultValue` if change it a little:

`  private void ValidateQueryArgumentDefaultValue(QueryArgument argument, Func<string> error)`

Comment (sungam3r) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:250]: For another code in `VisitInputObjectFieldDefinition` it will not be so comfortable so let's keep it as is.

File: src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs [hunk 86]
```diff
@@ -233,6 +238,28 @@ public override void VisitDirectiveArgumentDefinition(QueryArgument argument, Di
...
+        }
+
+        private void ValidateQueryArgumentDefaultValue(QueryArgument argument, FieldType field, INamedType type)
+        {
+            if (argument.DefaultValue is GraphQLValue value)
+            {
+                argument.DefaultValue = Execution.ExecutionHelper.CoerceValue(argument.ResolvedType, Language.CoreToVanillaConverter.Value(value)).Value;
```
Comment (sungam3r) [inline src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:257]: Please add note in class summary about possible modification of default values for arguments and input object fields.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs [hunk 87]
```diff
@@ -62,39 +62,61 @@ public void AddValue(EnumValueDefinition value)
...
                 return null;
-            }
 
-            var found = Values.FindByName(value.ToString());
-            return found?.Value;
+            var foundByValue = Values.FindByValue(value);
+            if (foundByValue == null)
+                ThrowSerializationError(value);
+
+            return foundByValue.Name;
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/EnumerationGraphType.cs:106]:
```suggestion
            var foundByValue = Values.FindByValue(value);
            return foundByValue == null
                ? ThrowSerializationError(value)
                : foundByValue.Name;
```

Also remove `FindByName`. I was used only here and it is `internal`.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs [hunk 88]
```diff
@@ -62,39 +62,61 @@ public void AddValue(EnumValueDefinition value)
...
-            var serialized = (string)Serialize(value);
-            return serialized != null ? new EnumValue(serialized) : null;
+            if (value == null)
+                return new NullValue();
+
+            var foundByValue = Values.FindByValue(value);
+            if (foundByValue == null)
+                ThrowASTConversionError(value);
+
+            return new EnumValue(foundByValue.Name);
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/EnumerationGraphType.cs:119]:
```suggestion
            var foundByValue = Values.FindByValue(value);
            return foundByValue == null
                ? ThrowASTConversionError(value)
                : new EnumValue(foundByValue.Name);
```

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 87 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:106]: 🤦 I see other usages here.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs [hunk 89]
```diff
@@ -62,39 +62,61 @@ public void AddValue(EnumValueDefinition value)
...
+        {
+            EnumValue enumValue => Values.FindByName(enumValue.Name) != null,
+            NullValue _ => true,
+            _ => false
+        };
+
+        /// <inheritdoc/>
+        public override object ParseValue(object value) => value switch
+        {
+            string s => Values.FindByName(s)?.Value ?? ThrowValueConversionError(value),
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: 🤔 OK. With literals everything is clear but I think that for `ParseValue`/`CanParseValue` it is legal to have case with enum internal value and just return this value (without boxing as usual).

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs [hunk 90]
```diff
@@ -123,5 +124,38 @@ public void does_not_allow_nulls_to_be_added()
         {
             Assert.Throws<ArgumentNullException>(() => new EnumerationGraphType().AddValue(null));
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: @Shane32 Check this test case, please. If I understand correctly now we allow to have `null` as internal value for enums.

Comment (sungam3r) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: Side note 1:
```csharp
 protected override string ChangeEnumCase(string val)
            {
                return new string(val.Select(c => char.IsUpper(c) ? char.ToLower(c) : char.ToUpper(c)).ToArray());
            }
```
->
```csharp
 protected override string ChangeEnumCase(string val) => val.ToUpper();
```

Comment (sungam3r) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: Side note 2, new test:
```csharp
        [Fact]
        public void parses_from_value()
        {
            type.ParseValue(Colors.Red).ShouldBe(Colors.Red);
        }
```

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs [hunk 91]
```diff
@@ -123,5 +124,38 @@ public void does_not_allow_nulls_to_be_added()
...
+        public void serialize_by_value()
+        {
+            type.Serialize(Colors.Red).ShouldBe("RED");
+        }
+
+        [Fact]
+        public void serialize_by_underlying_value()
+        {
+            type.Serialize((int)Colors.Red).ShouldBe("RED");
+        }
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:144]:
```suggestion
        [Fact]
        public void serialize_by_underlying_value()
        {
            type.Serialize((int)Colors.Red).ShouldBe("RED");
        }
        
        [Fact]
        public void serialize_by_value()
        {
            type.Serialize(Colors.Red).ShouldBe("RED");
        }
```

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs [hunk 92]
```diff
@@ -123,5 +124,38 @@ public void does_not_allow_nulls_to_be_added()
...
+
+        [Fact]
+        public void serialize_by_name_throws()
+        {
+            Should.Throw<InvalidOperationException>(() => type.Serialize("RED"));
+        }
+
+        [Fact]
+        public void toAST_returns_enum_value()
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:153]: \+ test for returning `NullValue` for `null` input ?

File: src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs [hunk 93]
```diff
@@ -39,7 +39,7 @@ private void AssertQueryWithError(string query, string result, string message, i
         public void Custom_Enum_Numbered_From_Name() => AssertQuerySuccess("{ customEnumSleepy }", @"{ ""customEnumSleepy"": ""ISSLEEPY"" }");
 
         [Fact]
-        public void String_Enum() => AssertQuerySuccess("{ sleepy }", @"{ ""sleepy"": ""SLEEPY"" }");
+        public void String_Enum() => AssertQueryWithError("{ sleepy }", @"{ ""sleepy"": null }", "Error trying to resolve field 'sleepy'.", 1, 3, "sleepy", exception: new InvalidOperationException());
```
Comment (sungam3r) [inline src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs:42]: Empty `InvalidOperationException`?

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 94]
```diff
@@ -0,0 +1,807 @@
...
+        [InlineData(typeof(GuidGraphType))]
+        [InlineData(typeof(FloatGraphType))]
+        [InlineData(typeof(DecimalGraphType))]
+        [InlineData(typeof(EnumerationGraphType))]
+        public void allow_null(Type graphType)
+        {
+            var g = (ScalarGraphType)graphType.GetConstructor(Type.EmptyTypes).Invoke(null);
+            g.ParseValue(null).ShouldBeNull();
+            g.CanParseValue(null).ShouldBeTrue();
+            g.ParseLiteral(new NullValue()).ShouldBeNull();
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:65]: Somewhere here should be test for   `g.ParseLiteral(null)` and `g.CanParseLiteral(null)`

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 95]
```diff
@@ -0,0 +1,807 @@
...
+        [InlineData(typeof(IdGraphType))]
+        [InlineData(typeof(StringGraphType))]
+        [InlineData(typeof(UriGraphType))]
+        [InlineData(typeof(GuidGraphType))]
+        [InlineData(typeof(FloatGraphType))]
+        [InlineData(typeof(DecimalGraphType))]
+        [InlineData(typeof(EnumerationGraphType))]
+        public void allow_null(Type graphType)
+        {
+            var g = (ScalarGraphType)graphType.GetConstructor(Type.EmptyTypes).Invoke(null);
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:62]: Can be extracted into test helper
```csharp
public static ScalarGraphType Create(this Type graphType) =>  (ScalarGraphType)graphType.GetConstructor(Type.EmptyTypes).Invoke(null);
```

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 96]
```diff
@@ -0,0 +1,807 @@
...
+        [InlineData(typeof(IntGraphType), -2000000000)] //float cannot hold the full precision of int
+        [InlineData(typeof(IntGraphType), 0)]
+        [InlineData(typeof(IntGraphType), 2000000000)]
+        [InlineData(typeof(UIntGraphType), 0u)]
+        [InlineData(typeof(UIntGraphType), 4000000000u)]
+        [InlineData(typeof(LongGraphType), -9223300018843156480L)]
+        [InlineData(typeof(LongGraphType), 0L)]
+        [InlineData(typeof(LongGraphType), 9223300018843156480L)]
+        [InlineData(typeof(ULongGraphType), 0ul)]
+        [InlineData(typeof(ULongGraphType), 18446700093244440576uL)]
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:116]:
```suggestion
        [InlineData(typeof(ULongGraphType), 18446700093244440576UL)]
```

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 97]
```diff
@@ -0,0 +1,807 @@
...
+                        converted = new BigInteger((decimal)Convert.ChangeType(value, typeof(decimal)));
+                    }
+                    else
+                    {
+                        converted = Convert.ChangeType(value, type);
+                    }
+                }
+                catch
+                {
+                    continue;
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:157]: ?

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 92 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:153]: Should be Covered in allscalars tests

File: src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs (hunk 93 above)
Comment (Shane32) [reply src/GraphQL.Tests/Bugs/Bug1699InvalidEnum.cs:42]: Empty because it just uses the code

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 97 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:157]: e.g. testing the value 500 being passed as a byte is not possible.  so it skips testing the data types where the conversion of the value to the specific data type in the loop fails

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 94 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:65]: Those values are undefined.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 98]
```diff
@@ -0,0 +1,807 @@
...
+                    byte b => new IntValue(b),
+                    short s => new IntValue(s),
+                    ushort us => new IntValue(us),
+                    int i => new IntValue(i),
+                    uint ui => new LongValue(ui),
+                    long l => new LongValue(l),
+                    ulong ul => new BigIntValue(ul),
+                    BigInteger bi => new BigIntValue(bi),
+                    float f => new FloatValue(f),
+                    double d => new FloatValue(d),
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:452]: Now I think it is really better to create the same AST value type from `ToAST` method. It turns out a result that is easier to check.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 94 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:65]: Added test

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 99]
```diff
@@ -0,0 +1,807 @@
...
+        [InlineData(typeof(IdGraphType), 2, 2)]
+        [InlineData(typeof(IdGraphType), "3", "3")]
+        [InlineData(typeof(FloatGraphType), 3.5, 3.5)]
+        public void parseValue_other_ok(Type graphType, object value, object parsed)
+        {
+            var g = (ScalarGraphType)graphType.GetConstructor(Type.EmptyTypes).Invoke(null);
+            var ret = g.ParseValue(value);
+            ret.ShouldBeOfType(parsed.GetType());
+            ret.ShouldBe(parsed);
+            g.CanParseValue(value).ShouldBeTrue();
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:503]: In general, it seems more logical in all tests first call `CanXXX` and only then `XXX`.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 100]
```diff
@@ -0,0 +1,807 @@
...
+        [InlineData(typeof(UShortGraphType), 1.5)]
+        [InlineData(typeof(IntGraphType), 1.5)]
+        [InlineData(typeof(UIntGraphType), 1.5)]
+        [InlineData(typeof(LongGraphType), 1.5)]
+        [InlineData(typeof(ULongGraphType), 1.5)]
+        [InlineData(typeof(BigIntGraphType), 1.5)]
+        public void parseValue_other_fail(Type graphType, object value)
+        {
+            var g = (ScalarGraphType)graphType.GetConstructor(Type.EmptyTypes).Invoke(null);
+            Should.Throw<Exception>(() => g.ParseValue(value));
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:579]: Let's test exact exception type - `InvalidOperation` or `Format` via one more method parameter.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 101]
```diff
@@ -0,0 +1,807 @@
...
+                int i => new IntValue(i),
+                long l => new LongValue(l),
+                bool b => new BooleanValue(b),
+                double d => new FloatValue(d),
+                string s => new StringValue(s),
+                _ => null
+            };
+
+            var g = (ScalarGraphType)graphType.GetConstructor(Type.EmptyTypes).Invoke(null);
+            Should.Throw<Exception>(() => g.ParseLiteral(astValue));
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:624]: Let's test exact exception type - `InvalidOperation` or `Format` via one more method parameter.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs [hunk 102]
```diff
@@ -0,0 +1,807 @@
...
+        [InlineData(typeof(UShortGraphType), 1.5)]
+        [InlineData(typeof(IntGraphType), 1.5)]
+        [InlineData(typeof(UIntGraphType), 1.5)]
+        [InlineData(typeof(LongGraphType), 1.5)]
+        [InlineData(typeof(ULongGraphType), 1.5)]
+        [InlineData(typeof(BigIntGraphType), 1.5)]
+        public void serialize_other_fail(Type graphType, object value)
+        {
+            var g = (ScalarGraphType)graphType.GetConstructor(Type.EmptyTypes).Invoke(null);
+            Should.Throw<Exception>(() => g.Serialize(value));
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:659]: Let's test exact exception type - `InvalidOperation` or `Format` via one more method parameter.

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 90 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: > null as internal value

ok we could add that feature.

> change enum case

That code is designed to allow tests for custom cased enumeration members.  But the test class is completely unused.  I don't know why it's there.  Do you want me to delete it?  Certainly changing it to be uppercase defeats the purpose of the class.

> new test

parses_from_value would fail.  Externally it is represented as a string.  Does this need to be changed?

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 89 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: In generally, I really don't think our implementations of ParseValue should allow internally represented values to be parsed.  Often it doesn't "matter" because they are different .NET types, but here it's even worse: a string could be the internally or externally represented value.

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 92 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:153]: изображение

Comment (Shane32) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:153]: Do you want me to change the comment?

**Comment by Shane32** [comment]
> > I tried, but it won't work - it would have to be static. Or we make more internal methods
> 
> Only one method changes from `protected` to `protected internal`. Not?

That's neither here nor there.  You cannot access an instance member without holding a reference to an instance.

1. I can create a static instance to a random graph type just so we can call the internal instance method on the abstract scalar graph type.
2. I can change the throw method to be `protected internal static`
3. I can create another method that's `internal static` (e.g. Throw...Internal) and the `protected` methods call the static method.

I cannot simply add `internal`.  Option 2 is the only option even worth considering, unless we make the methods virtual, which currently they are not.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 102 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:659]: No.  This is a general catch-all for some different error conditions that I can throw in a big list.  If we want individual checks, they should be in individual xxxGraphTypeTests file.  I have already updated many checks there each with different type checking capability.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 101 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:624]: No. This is a general catch-all for some different error conditions that I can throw in a big list. If we want individual checks, they should be in individual xxxGraphTypeTests file. I have already updated many checks there each with different exception type checking capability.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 100 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:579]: No. This is a general catch-all for some different error conditions that I can throw in a big list. If we want individual checks, they should be in individual xxxGraphTypeTests file. I have already updated many checks there each with different exception type checking capability.

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 90 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: > Do you want me to delete it?

Yes.

>  Certainly changing it to be uppercase defeats the purpose of the class.

Aaaaa :) 🤦‍♂️

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 99 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:503]: I can reorder these instructions if you like.  But they all need to be tested.  We do not have a requirement that CanParse is called before Parse, and the code does not work that way.

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 90 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: >  Externally it is represented as a string. Does this need to be changed?

I think that externally enum **can** be represented as enum. See `GuidGraphType.ParseValue` or `UriGraphType.ParseValue`. Both accept their `native` types. Why not to do so with enums?

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 92 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:153]: Right below that it already states:
>  Does test ALL scalars' handling of null

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 89 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: > In general, I really don't think our implementations of ParseValue should allow internally represented values to be parsed. 

Now it does. And IMO it's right.

I undestand it. Agree. But let's separate "arbitrary" internally represented values from "native" internally represented values. For enums it is ofter absolutely normal to be represented as .NET Enums as internal values. The same for `System.Uri` for `UriGraphType`. Of course there can be some issues with exotic custom scalars but these are not our problems. We gave the opportunity to override the behavior for any scalar.

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 92 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:153]: > Do you want me to change the comment?

No. I did not notice `[InlineData(typeof(EnumerationGraphType))]` case. OK.

**Comment by sungam3r** [comment]
Maybe we are talking about different things. I'm talking about 
изображение

> You cannot access an instance member without holding a reference to an instance.

I see `scalar` instance.

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 102 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:659]: OK

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 100 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:579]: OK

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 101 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:624]: OK

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 99 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs:503]: I know. As you see fit.

**Comment by Shane32** [comment]
> Maybe we are talking about different things.

Yes, or maybe I just wasn't thinking yesterday when I was working on it!  I can fix that.

**Comment by Shane32** [comment]
Done :+1:

File: src/GraphQL.Tests/Types/CustomScalarTests.cs [hunk 103]
```diff
@@ -0,0 +1,261 @@
...
+        [InlineData("hello", "hello")]     // serializing "hello" should return "hello"
+        public void Serialize(string internalValue, string externalValue)
+        {
+            var c = new CustomScalar();
+            // try serializing
+            c.Serialize(internalValue).ShouldBe(externalValue);
+        }
+
+        [Theory]
+        [InlineData(null, "externalNull")] // serializing null should return "externalNull" (inverse of parsing)
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/CustomScalarTests.cs:46]: Are comments copy-pasted from Serialize?

Comment (Shane32) [reply src/GraphQL.Tests/Types/CustomScalarTests.cs:46]: lol probably!

Comment (Shane32) [reply src/GraphQL.Tests/Types/CustomScalarTests.cs:46]: let me look and see....

Comment (Shane32) [reply src/GraphQL.Tests/Types/CustomScalarTests.cs:46]: ok, yes they are, but only because it's accurate, just as above where the parseliteral and parsevalue comments are the same

Comment (Shane32) [reply src/GraphQL.Tests/Types/CustomScalarTests.cs:46]: I wrote a lot of comments in this file because I knew it would be hard to understand what was being tested, or why it worked the way it did.

Comment (sungam3r) [reply src/GraphQL.Tests/Types/CustomScalarTests.cs:46]: ok

File: src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs (hunk 95 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/AllScalarGraphTypeTests.cs]: Done

File: src/GraphQL.Tests/Bugs/Bug1773.cs (hunk 78 above)
Comment (Shane32) [reply src/GraphQL.Tests/Bugs/Bug1773.cs:61]: We can work on this, but it should be done within a separate PR.  This PR is getting too big, and it will be hard to understand the consequences of additional changes.

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 90 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: I do not think Guid or Uri should allow Guid or Uri externally.

Comment (Shane32) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: At least with Guid or Uri there is no possibility of ambiguity.  Here there is.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 89 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: This seems like a security hole.

File: src/GraphQL.Tests/Bugs/Bug1773.cs (hunk 78 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Bugs/Bug1773.cs:61]: Agree.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs [hunk 104]
```diff
@@ -62,39 +62,59 @@ public void AddValue(EnumValueDefinition value)
...
+            null => null,
+            _ => ThrowValueConversionError(value)
+        };
```
Comment (Shane32) [inline src/GraphQL/Types/Scalars/EnumerationGraphType.cs:86]: This is what's needed to also parse internal values:

```suggestion
        public override object ParseValue(object value)
        {
            if (value is string s)
            {
                //search externally represented values
                var match2 = Values.FindByName(s);
                if (match2 != null)
                    return match2.Value;
            }

            if (value == null)
                return null;

            //search internally represented values
            var match = Values.FindByValue(value);
            if (match != null)
                return match.Value;

            return ThrowValueConversionError(value);
        }
```

File: src/GraphQL.Tests/Bugs/Bug1773.cs (hunk 77 above)
Comment (Shane32) [reply src/GraphQL.Tests/Bugs/Bug1773.cs:55]: See #2354

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 90 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: Imagine hand-crafted variables (inputs). After all, the specification does not say that variables should be formed only in the process of deserialization. Variables are simply coming from "somewhere". For example, you can read from the file or receive from other program/method. The variables can be already of necessary (internal) types. The specification says that variables can be of some runtime-type. In general, I think it cannot clearly hold the border between the external representation and internal. It all depends on who and how these variables creates. That is why the specification leaves a wider space for options compared to literals. So IMO it is **absolutely** normal to accept Guid, Uri, Enum or some other .NET types in `ParseValue` methods.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 89 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: Where exactly?

File: src/GraphQL/GraphQLExtensions.cs (hunk 82 above)
Comment (Shane32) [reply src/GraphQL/GraphQLExtensions.cs:577]: Maybe something like this?

```suggestion
                {
                    if (value == null)
                    {
                        throw new InvalidOperationException($"Null value provided for nonnull type '{nonnull}'.");
                    }
                    else
                    {
                        throw new InvalidOperationException($"Unable to get a nonnull AST representation of nonnull type '{nonnull}' for value '{value}'.");
                    }
                }
```

File: src/GraphQL/Types/Scalars/DateGraphType.cs (hunk 83 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/DateGraphType.cs:35]: Probably.  Should we change it?  I like the detailed error message.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 104 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:86]: Hmm. maybe move `f (value == null)            return null;` after `FindByValue` block right before ThrowValueConversionError ?

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:86]: Then enumeration will support `null` as internal value.

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:86]: 🤦 No. `FindByValue(null)` yields match which `Value` will be `null` :)

File: src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs (hunk 86 above)
Comment (Shane32) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:257]: Done; please review

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 104 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:86]: So... I suggest to move null check at the very beginning.

**Comment by Shane32** [comment]
I believe I answered all the questions that are awaiting an answer.  Lmk if I missed anything (I probably did).

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 104 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:86]: An appropriate test would need to be added as well, of course, like the sample provided above:

```cs
        [Fact]
        public void parses_from_value()
        {
            type.CanParseValue(Colors.Red).ShouldBeTrue();
            type.ParseValue(Colors.Red).ShouldBe(Colors.Red);
        }
```

File: src/GraphQL/GraphQLExtensions.cs (hunk 82 above)
Comment (sungam3r) [reply src/GraphQL/GraphQLExtensions.cs:577]: I don't like messages like `nonnull type XXX!`. Because of them it always seems to me that there may be a `XXX!!` type.

File: src/GraphQL.Tests/Types/TimeSpanMillisecondsGraphTypeTests.cs (hunk 81 above)
Comment (Shane32) [reply src/GraphQL.Tests/Types/TimeSpanMillisecondsGraphTypeTests.cs:95]: #2355

File: src/GraphQL/Types/Scalars/DateGraphType.cs (hunk 83 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/DateGraphType.cs:35]:
```suggestion
            _ => throw new InvalidOperationException($"Could not parse date. Expected either a string or a DateTime without time component. Value: {value}")
```
Tests may need to change also.

File: src/GraphQL/GraphQLExtensions.cs (hunk 82 above)
Comment (sungam3r) [reply src/GraphQL/GraphQLExtensions.cs:577]: I updated my initial suggestion.

File: src/GraphQL/Types/Scalars/DateGraphType.cs (hunk 83 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/DateGraphType.cs:35]: Basically it's legal to throw any exception from scalar's method. I see many `OverflowException` for example. We may keep here `FormatException` as is. But remember that exception then will be passed to response writer which calculates error code - `FORMAT`/`INVALID_OPERATION`/`OVERFLOW`. In some cases, it is beneficial to have fewer codes for the caller, in some more. I have no strict opinion here.

File: src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs (hunk 86 above)
Comment (sungam3r) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:259]: Good.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 89 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: Letting external values be parsed as internal values is generally considered a security hole.  Yesterday Microsoft released patches for zero-day attacks against Exchange due to an "insecure deserialization vulnerability".  Here we are validating it against a list of internal values, so to answer your question, "Nowhere exactly.".  But it feels like a security hole.

There's just no reason for any external values to be parsed as internal values.  There's no way for a value to be serialized via Serialize and then be deserialized via ParseValue that would require being able to parse internal values.  There's no way for json -- the transport of choice for graphql -- to carry an .NET enumeration type to be parsed at all.  And even if it did, it should be parsed as an external value, not as an internal value.

Why should a graphql endpoint respond to `{ widgets(color: 1) }` ?  What if next week RED was redefined as 2 instead of 1?  The whole point of having enumeration members strongly defined within the schema is to allow internal changes without breaking client applications.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 104 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:86]: Agree.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 89 above)
Comment (Shane32) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: To be precise, the example would be `query ($arg: MyEnum) { widgets (color: $arg) }` and passing `{ "arg": 1}` as the variables.  Since we already don't allow the number passed in the the literal.

And speaking of which, why is there any semantic difference parsing a literal vs a value?  Either way is parsing a value from a request.  There should be no semantic difference to the application.

So if you allowed ParseValue to contain the internal value 1, you should also allow the literal to parse the value 1.  Which again I see no reason to do.

In short, it completely breaks validation of a query against a schema to allow parsing by internal values.

I don't mind allowing native types within ParseValue for Guid/Uri/DateTime/DateTimeOffset because you can consider the values as external values -- in another format.  Just like receiving a double for a decimal graph type -- no problem, coerce the type.  But parsing an enum against an internal list of values is not the same thing.

File: src/GraphQL/Execution/ExecutionStrategy.cs [hunk 105]
```diff
@@ -340,42 +340,15 @@ protected virtual void SetArrayItemNodes(ExecutionContext context, ArrayExecutio
...
-                        }
-                        else if (node is ArrayExecutionNode arrayNode)
-                        {
-                            SetArrayItemNodes(context, arrayNode);
-                        }
-                        else if (node is ValueExecutionNode valueNode)
-                        {
-                            node.Result = valueNode.GraphType.Serialize(d)
-                                ?? throw new InvalidOperationException($"Unable to serialize '{d}' to '{valueNode.GraphType.Name}' for list index {index}.");
-                        }
```
Comment (sungam3r) [inline src/GraphQL/Execution/ExecutionStrategy.cs:362]: Good.

File: src/GraphQL/Types/Scalars/EnumerationGraphType.cs (hunk 89 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: > There's just no reason for any external values to be parsed as internal values.

My point is that for variables we cannot say for sure what is `internal` and `external` values.

> There's no way for json -- the transport of choice for graphql -- to carry an .NET enumeration type to be parsed at all. 

Forget about JSON. This is just one of the sources. Think about the fact that the variables can simply be created programmatically. In the end, this is the essence of the runtime - the runtime/platform on which the application is running.

> So if you allowed ParseValue to contain the internal value 1, you should also allow the literal to parse the value 1. 

Absolutely no. Literal is a part of GraphQL language. Variables are transport/platform specific. Also keep in mind that there may be no any transport at all.

> I don't mind allowing native types within ParseValue for Guid/Uri/DateTime/DateTimeOffset because you can consider the values as external values -- **in another format**. Just like receiving a double for a decimal graph type -- no problem, coerce the type. But parsing an enum against an internal list of values is not the same thing.

Why that argument about _just another format_ cannot be applied to enums ?

I suggest to add a new issue pointing to that thread and go on with this PR.

Comment (Shane32) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: #2356

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/EnumerationGraphType.cs:83]: good

File: src/GraphQL.Tests/Types/IdGraphTypeTests.cs [hunk 106]
```diff
@@ -11,41 +11,108 @@ public class IdGraphTypeTests
...
         [Fact]
-        public void parse_literal_long_value_to_identifier()
+        public void serialize_guid()
         {
-            long val = 12345;
-            _type.ParseLiteral(new LongValue(12345)).ShouldBe(val);
+            var g = new Guid("12345678901234567890123456789012");
+            var ret = _type.Serialize(g);
+            ret.ShouldBeOfType(typeof(string));
+            ret.ShouldBe(g.ToString("D", CultureInfo.InvariantCulture));
```
Comment (sungam3r) [inline src/GraphQL.Tests/Types/IdGraphTypeTests.cs:115]:
```suggestion
            ret.ShouldBe(g.ToString("D", System.Globalization.CultureInfo.InvariantCulture));
```

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 5 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs]: I'm OK with current state.

File: src/GraphQL/Types/Scalars/ScalarGraphType.cs (hunk 8 above)
Comment (sungam3r) [reply src/GraphQL/Types/Scalars/ScalarGraphType.cs]: Already resolved.

File: src/GraphQL.Tests/Types/EnumGraphTypeTests.cs (hunk 90 above)
Comment (sungam3r) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: Did you delete class?

Comment (Shane32) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:125]: No I forgot.

Comment (Shane32) [reply src/GraphQL.Tests/Types/EnumGraphTypeTests.cs:112]: Done

**Review by sungam3r — APPROVED** [review]
I watched all the files, some many times, because they changed. I did not watch in detail only `CustomScalarTests`. Now I'm tired and I need to relax. I think it will not be a big difference if I do not see this remaining file in detail. It was a very long adventure. We will do other work related to error messages and scalars later.
