### PR TITLE
Schema builder fixes; add schema validation of subscription fields

### LINKED ISSUE #3580: Ensure that StreamResolver IS set for the Schema.Subscription graph type
See #3574

### PR DESCRIPTION
**Pull request by Shane32**
Fixes #3580 

Adds schema validation to ensure that `StreamResolver` is set for fields of root subscription types.  This is a non-breaking change because without the validation, attempting to resolve these fields would fail at runtime.

Trying to write a fix for #3580 I found two bugs in the schema-first SchemaBuilder (as far as I can tell).
- `Include` does not include configurations via `ForAll`
- Subscriptions don't work properly when the `schema` definition is listed after the subscription definition

### CODE REVIEW

File: src/GraphQL/Utilities/SchemaBuilder.cs [hunk 1]
```diff
@@ -111,14 +111,19 @@ private Schema BuildSchemaFrom(GraphQLDocument document)
 
             var directives = new List<Directive>();
 
+            // process the schema definition first
             foreach (var def in document.Definitions)
             {
                 if (def is GraphQLSchemaDefinition schemaDef)
                 {
                     _schemaDef = schemaDef;
```
Comment (Shane32) [inline src/GraphQL/Utilities/SchemaBuilder.cs:119]: `_schemaDef` must be set first or setting subscription resolvers don't get set properly.  Who knows maybe more stuff.

File: src/GraphQL/Utilities/TypeSettings.cs [hunk 2]
```diff
@@ -74,7 +74,7 @@ public void Include(Type type)
         /// </summary>
         public void Include(string name, Type type)
         {
-            _typeConfigurations[name].Type = type;
+            For(name).Type = type;
```
Comment (Shane32) [inline src/GraphQL/Utilities/TypeSettings.cs:77]: `ForAll` only triggers when using `For`, but seems to clearly indicate that it should operate on all types.  So I've changed `Include` to call `For` and thereby execute any configured `ForAll` code.

File: src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs [hunk 3]
```diff
@@ -238,6 +238,14 @@ public override void VisitSchema(ISchema schema)
             var n3 = schema.Subscription?.Name;
             if (n1 == n2 && n1 != null || n1 == n3 && n1 != null || n2 == n3 && n2 != null)
                 throw new InvalidOperationException("The query, mutation, and subscription root types must all be different types if provided.");
+            if (schema.Subscription != null)
+            {
+                foreach (var field in schema.Subscription.Fields.List)
+                {
+                    if (field.StreamResolver == null)
+                        throw new InvalidOperationException($"The field '{field.Name}' of the subscription root type '{schema.Subscription.Name}' must have StreamResolver set. You should set StreamResolver only all root fields of subscriptions.");
```
Comment (gao-artur) [inline src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:246]: Typo? Should it be `on` instead of `all`?

Comment (gao-artur) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:246]: In general, fixing these errors one by one is pretty hard because it requires restarting the application multiple times. I think gathering all the errors and throwing single/aggregated exception after the full validation can provide a better experience. This is usually not a problem during development but is annoying during the version upgrade.

Comment (Shane32) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:246]: Ok let's make that change for v8.  Do you want me to continue with this PR or just add this validation into v8?

Comment (Shane32) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:246]:
```suggestion
                        throw new InvalidOperationException($"The field '{field.Name}' of the subscription root type '{schema.Subscription.Name}' must have StreamResolver set.");
```

Comment (Shane32) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs:246]: > Ok let's make that change for v8. Do you want me to continue with this PR or just add this validation into v8?

Well, it's not like the schema will work properly if this were to fail validation, so might as well leave it in here.

Comment (gao-artur) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs]: Throwing aggregated error is a job for separate PR

**Review by gao-artur — APPROVED** [review]

File: src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs (hunk 3 above)
Comment (Shane32) [reply src/GraphQL/Utilities/Visitors/SchemaValidationVisitor.cs]: #3875
