### PR TITLE
Fix for GraphQLExtensions.GetNamedType/IsInputType/IsOutputType

### LINKED ISSUE #1837: InputGraphType checks field types based on Resolved Type only.
## Description

When you add a field to an InputObjectGraphType it verifies if the type and field is also an input type. But it uses only the ResolvedType property for that. If you use the generic version of the types the ResolvedType is not resolved yet and therefore throws an exception.

### Steps to reproduce

```
public class InputDroidType : InputObjectGraphType
{
  public InputDroidType()
  {
    Field<NonNullGraphType<IdGraphType>>("id");
    Field<ListGraphType<StringGraphType>>("weapons");
  }
}
```

Version: 3.0.0

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #1837

### CODE REVIEW

File: src/GraphQL/GraphQLExtensions.cs [hunk 1]
```diff
@@ -107,33 +110,54 @@ public static bool IsOutputType(this Type type)
...
-            {
-                NonNullGraphType nonNull => GetNamedType(nonNull.ResolvedType),
-                ListGraphType list => GetNamedType(list.ResolvedType),
-                _ => type
-            };
+            if (type == null)
+                return null;
+
+            var (namedType, _) = type.GetNamedTypes();
+            return namedType ?? throw new NotSupportedException("Please set ResolvedType property before calling this method or call GetNamedType(this Type type) instead");
```
Comment (sungam3r) [inline src/GraphQL/GraphQLExtensions.cs:160]: A key part of this PR. The `GetNamedType(this IGraphType type)` method was only intended for use by unwrapping other resolved types. The `GetNamedType(this Type type)` method has no problems in this regard. After throwing the exception, I saw that the calling methods needed to be changed. Typically, they didn't need the type itself. Only in one case did I have to actually create a type. See `SchemaTypes`. We had no errors all this time because we did not configure the graph types this way.

**Review by Shane32 — APPROVED** [review]
