### PR TITLE
UInt/UShort/Short scalars fix

### LINKED ISSUE #1073: Why there are no [Guid,Short,UInt,ULong,UShort]GraphType in GraphTypesLookup ctor?
Do I understand correctly that all known types of scalars should be initialized there?
Alse why `GuidGraphType`, `ShortGraphType`, `UIntGraphType`, `ULongGraphType` types do not have name set in the constructor? All other scalars have their name set in the constructor.

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #1073
add two scalars - Byte and SByte

### CODE REVIEW

File: src/GraphQL/Types/UIntGraphType.cs [hunk 1]
```diff
@@ -4,19 +4,31 @@ namespace GraphQL.Types
...
+            {
+                case UIntValue uintValue:
+                    return uintValue.Value;
+
+                case IntValue intValue:
+                    if (intValue.Value >= 0)
+                        return (uint)intValue.Value;
+                    return null;
+
+                case LongValue longValue:
```
Comment (sungam3r) [inline src/GraphQL/Types/UIntGraphType.cs]: Value can come in two containers - `IntValue` and `LongValue` (if overflow Int)

File: src/GraphQL/Types/ULongGraphType.cs [hunk 2]
```diff
@@ -4,19 +4,31 @@ namespace GraphQL.Types
...
+            {
+                case ULongValue ulongValue:
+                    return ulongValue.Value;
+
+                case IntValue intValue:
+                    if (intValue.Value >= 0)
+                        return (ulong)intValue.Value;
+                    return null;
+
+                case LongValue longValue:
```
Comment (sungam3r) [inline src/GraphQL/Types/ULongGraphType.cs]: Value can come in two containers - `IntValue` and `LongValue` (if overflow Int)
