### PR TITLE
Unify scalar conversions

### LINKED ISSUE #2047: FloatGraphType arguments can be parsed as integers
I'm running into an issue where a Float is coming through into the `Arguments` dictionary as an `int`. My code expects it to be a `double` and fails on the downcast. It looks like `FloatGraphType` should have

        public override object ParseLiteral(IValue value) => value switch
        {
            FloatValue floatVal => floatVal.Value,
            IntValue intVal => intVal.Value,
            LongValue longVal => longVal.Value,
            _ => null
        };

changed to

        public override object ParseLiteral(IValue value) => value switch
        {
            FloatValue floatVal => floatVal.Value,
            IntValue intVal => ParseValue(intVal.Value),
            LongValue longVal => ParseValue(longVal.Value),
            _ => null
        };

in line with the other numeric scalar types. I can send a PR if we agree this is a bug.

### PR DESCRIPTION
**Pull request by sungam3r**
Fixes #2047 . Also fixes bug when `FloatGraphType.Value` cannot be casted to `float` even when fractional part was specified.
I decided to remove all `Convert.To` calls and use the `checked` operator explicitly. First, this is how our intentions are more clearly expressed. Secondly, it turned out that we left unchecked context (C# uses unchecked by default) in some places. Examples:
```
 Register<sbyte, byte>(value => (byte)value);
 Register<sbyte, ulong>(value => (ulong)value);
```

I didn't add tests for all cases, because it is very expensive. I became convinced that some existing tests started failing when I changed `Convert.To` calls to explicit cast operator. So I added `checked` in every line with downcast.

### CODE REVIEW

**Comment by sungam3r** [comment]
#2048 may be done in this PR too. @Shane32 ?

File: src/GraphQL/Types/Scalars/LongGraphType.cs [hunk 1]
```diff
@@ -7,7 +7,7 @@ public class LongGraphType : ScalarGraphType
         public override object ParseLiteral(IValue value) => value switch
         {
             LongValue longValue => longValue.Value,
-            IntValue intValue => (long)intValue.Value,
+            IntValue intValue => ParseValue(intValue.Value),
```
Comment (sungam3r) [inline src/GraphQL/Types/Scalars/LongGraphType.cs:10]: Just to unify all scalars.

Comment (sungam3r) [reply src/GraphQL/Types/Scalars/LongGraphType.cs:10]: Could/should be reverted for #2048 .

**Comment by Shane32** [comment]
Regarding #2048, I would suggest that we include those changes in this PR, using value casts rather than performing dictionary lookups within the ValueConverter for these conversions.

File: src/GraphQL/Conversion/ValueConverter.cs [hunk 2]
```diff
@@ -57,79 +57,84 @@ static ValueConverter()
             Register<DateTimeOffset, DateTime>(value => value.UtcDateTime);
             Register<TimeSpan, long>(value => (long)value.TotalSeconds);
 
-            Register<int, sbyte>(value => Convert.ToSByte(value, NumberFormatInfo.InvariantInfo));
-            Register<int, byte>(value => Convert.ToByte(value, NumberFormatInfo.InvariantInfo));
-            Register<int, short>(value => Convert.ToInt16(value, NumberFormatInfo.InvariantInfo));
-            Register<int, ushort>(value => Convert.ToUInt16(value, NumberFormatInfo.InvariantInfo));
+            Register<int, sbyte>(value => { checked { return (sbyte)value; } });
```
Comment (Shane32) [inline src/GraphQL/Conversion/ValueConverter.cs:60]:
```suggestion
            Register<int, sbyte>(value => checked((sbyte)value));
```
I would suggest using the `checked` keyword rather than the `checked` block.

See: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked

File: src/GraphQL/Types/Scalars/FloatGraphType.cs [hunk 3]
```diff
@@ -9,8 +9,10 @@ public class FloatGraphType : ScalarGraphType
         public override object ParseLiteral(IValue value) => value switch
         {
             FloatValue floatVal => floatVal.Value,
-            IntValue intVal => intVal.Value,
-            LongValue longVal => longVal.Value,
+            IntValue intVal => ParseValue(intVal.Value),
```
Comment (Shane32) [inline src/GraphQL/Types/Scalars/FloatGraphType.cs:12]:
```suggestion
            IntValue intVal => (double)intVal.Value,
```
I suggest the above and similar for performance to eliminate a dictionary lookup.  Note that for a widening conversion like this one, `checked` is not necessary, but nor should it create a performance impact as the compiler would know that.  Alternate syntax:
```suggestion
            IntValue intVal => checked((double)intVal.Value),
```

**Comment by Shane32** [comment]
I don't see any tests to confirm that it will convert a literal of type decimal (e.g. "9223372036854775808") to a FloatValue of type double.  Are we not adding that?

File: src/GraphQL/Conversion/ValueConverter.cs (hunk 2 above)
Comment (sungam3r) [reply src/GraphQL/Conversion/ValueConverter.cs:60]: I read the same page and didn't notice it 🤦

**Comment by Shane32** [comment]
> I didn't add tests for all cases, because it is very expensive. I became convinced that some existing tests started failing when I changed `Convert.To` calls to explicit cast operator. So I added `checked` in every line with downcast.

I'm not really worried about test cases for all the overflow scenarios, etc.  I just feel that when there's an explicit issue/bug brought to our attention, we should make a point to add a test for the fix, to help ensure we never experience that bug again.  In this case, we should add a test to ensure that integer literals interpreted as FloatGraphType values return objects of type `double`, not `int`.  There is no new test for this, as far as I can tell.

**Comment by sungam3r** [comment]
In fact, I noticed that the situation is a little more complicated. See for example how ByteGraphType handles IntValue.
```
  public class ByteGraphType : ScalarGraphType
    {
        public override object ParseLiteral(IValue value) => value switch
        {
            ByteValue byteValue => byteValue.Value,
            IntValue intValue => byte.MinValue <= intValue.Value && intValue.Value <= byte.MaxValue ? (byte?)intValue.Value : null, 
            _ => null
        };

        public override object ParseValue(object value) => ValueConverter.ConvertTo(value, typeof(byte));
    }
```
I remembered that in case of conversion failure, we return null and this serves as an indication of the impossibility of conversion. It was your PR. Now I doubt if we should use an explicit cast under `checked` context. Now I don't understand how best to do it. I will listen to your thoughts. I will come back to this PR later.

**Comment by sungam3r** [comment]
I will add tests after I understand if I'm going in the right direction.

**Comment by Shane32** [comment]
If I remember correctly, we handle conversion exceptions also.  The null check is typically used if the conversion can't even be attempted.  I'll check and see.

**Comment by sungam3r** [comment]
> If I remember correctly, we handle conversion exceptions also.

I know. I began to be confused by the variety of approaches used - with and without throwing an exception, calling checks directly and through `ValueConverter`.

**Comment by Shane32** [comment]
I confirmed that exceptions thrown within `ParseLiteral` will be wrapped appropriately.  See link below.

https://github.com/graphql-dotnet/graphql-dotnet/blob/e76446be4318d83e279d77d22fce9fae0767f48d/src/GraphQL/Execution/ExecutionHelper.cs#L163..L175

File: src/GraphQL/Conversion/ValueConverter.cs (hunk 2 above)
Comment (Shane32) [reply src/GraphQL/Conversion/ValueConverter.cs:60]: At least you thought of it!  Coming from a VB.Net background, in which arithmetic is checked by default, I forget that arithmetic is unchecked by default in C#.

**Review by Shane32 — APPROVED** [review]

**Comment by Shane32** [comment]
Any reason why these changes should go in 3.3.0 vs 3.2.1?  Since valid queries might (properly) return a float instead of an int, it could change operation of existing working code.  On the other hand, it is certainly a bug fix, and should not have returned an int to begin with.

Just double checking @sungam3r before we release 3.2.1

**Comment by sungam3r** [comment]
3.3.0 ? It is 3.2.1. I bump patch number since there were no new or breaking changes in public APIs. 
изображение

**Comment by Shane32** [comment]
Just checking thanks
